### ISSUE TITLE
Can I change kDBPath from /tmp/** to a remote reliable source such as HDFS or GFS?

### ISSUE THREAD

**Issue by hfx123456** [facebook/rocksdb#10006]
If you have a example like this ，I will very I will appreciate your help very much

**Comment by hfx123456** [comment]
std::shared_ptr<FileSystem>* fs ,what it is ? I am not good at C++

**Comment by hfx123456** [comment]
how to use my own code to connect to the hdfs,rather than use the db_bench

**Comment by riversand963** [comment]
> std::shared_ptr* fs ,what it is 

https://en.cppreference.com/w/cpp/memory/shared_ptr may be helpful.

> how to use my own code to connect to the hdfs,rather than use the db_bench

Not related to RocksDB, but anyway: https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/LibHdfs.html.
To integrate with RocksDB, you need to use the APIs https://github.com/riversand963/rocksdb-hdfs-env/blob/master/env_hdfs.h#L97:L98 to obtain a smart pointer to `HDFSEnv` or `HDFSFs`, and pass it to `options` when you open the database.

Closing since HDFS is no longer officially supported in RocksDB main repo.

#wontfix

**Comment by ajkr** [comment]
please continue using the original issue, even if closed (#9997)
