### ISSUE TITLE
Should we provide std::unique_ptr for rocksdb::BackupEngine while BackupEngine::Open

### ISSUE THREAD

**Issue by YiteGu** [facebook/rocksdb#10638]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Steps to reproduce the behavior

In my function body：
``` 
void RocksDBStore::db_backup(const string& dst_dir)
{
  rocksdb::Status s;
  rocksdb::BackupableDBOptions bkOptions(dst_dir);
  bkOptions.backup_env = rocksdb::Env::Default();
  rocksdb::BackupEngine *backup_engine;

  s = rocksdb::BackupEngine::Open(env, bkOptions, &backup_engine);
  if (!s.ok()) {
    derr << s.ToString() << dendl;
    return;
  }
  backup_engine->CreateNewBackup(db);
  if (!s.ok()) {
    derr << s.ToString() << dendl;
    return;
  }
  delete backup_engine;
  backup_engine = nullptr;
}
```
Here define `rocksdb::BackupEngine` use normal pointer, if `CreateNewBackup` failed, backup_engine will be leak.
Should we provide `std::unique_ptr<BackupEngine>` to `BackupEngine::Open`?

**Comment by YiteGu** [comment]
@ajkr

**Comment by ajkr** [comment]
The `BackupEngine` leaks when `CreateNewBackup()` fails because that code path doesn't delete it.

You could use unique_ptr in your client code to ensure deletion even while the API takes a raw pointer, like this code does: https://github.com/facebook/rocksdb/blob/c5afbbfe4bf4ed97bf379bc605f3622c5630a5fa/utilities/backup/backup_engine_test.cc#L745-L748

**Comment by YiteGu** [comment]
thank you
