### ISSUE TITLE
Test cases are not compiled

### ISSUE THREAD

**Issue by darionyaphet** [facebook/rocksdb#10790]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Compile and generate test cases

### Actual behavior
Test cases are not compiled.

### Steps to reproduce the behavior

`cmake -DWITH_TESTS=ON -DWITH_ALL_TESTS=ON -DWITH_EXAMPLES=ON ..`

**Comment by jay-zhuang** [comment]
cmake and ctest works fine for me. There's even CI job using cmake and ctest to run all tests:
https://app.circleci.com/pipelines/github/facebook/rocksdb/19847/workflows/4974a2db-e4b8-4060-b05c-8947469e96fe/jobs/507064

https://github.com/facebook/rocksdb/blob/c76a90ceb97195135397c1e35bba4f24353b5be1/.circleci/config.yml#L207-L217

Please provide more information about the expected behavior.

**Comment by darionyaphet** [comment]
Hello, after build from source code it only generated files as follow:

```
block_cache_trace_analyzer_tool  CMakeCache.txt       db_bench        filter_bench      librocksdb.so        libtestharness.a   range_del_aggregator_bench  rocksdb.pc          third-party
build_version.cc                 CMakeFiles           db_stress_tool  hash_table_bench  librocksdb.so.7      Makefile           RocksDBConfig.cmake         table_reader_bench  tools
cache_bench                      cmake_install.cmake  examples        librocksdb.a      librocksdb.so.7.6.0  memtablerep_bench  RocksDBConfigVersion.cmake  Testing             trace_analyzer
```

Why is the test program not generated?  thanks
