### ISSUE TITLE
Loss values during high-rate write

### ISSUE THREAD

**Issue by amostyaev** [facebook/rocksdb#1096]
I'm using small rocksdb base to store one meta value for another big database.

Operations log is the following:
```
Put("key", "value0");
Put("key", "value1");
Put("key", "value2");
...
Put("key", "value9999");
```

Because key is only one, I want to reduce memory consumption and set the following opening options:
```
cf_opts.write_buffer_size = 16 * 1024;
cf_opts.target_file_size_base = 64 * 1024;
cf_opts.max_bytes_for_level_base = 64* 1024;
```

Rocksdb loses the last value after some amount of writes rocksdb. 

If I set the constants above to high values (16MB), all works fine.

Is that a bug or I forgot to set some other constant?

**Comment by dhruba** [comment]
It should have worked correctly. Do you see any errors in the log file? If there is any way for you to show us the LOG file, that would be great.

It will be best if you can write a small program that repeats the above mentioned steps and see if you can reproduce the same problem with your standalone program. If you can, please share the standalone program with us so that we can reproduce the same problem on our machine.

**Comment by amostyaev** [comment]
Here is the LOG link:
https://www.dropbox.com/s/j8dh5kkf2dgb2xm/LOG?dl=0
I didn't see any errors there. 

Sorry, but I can't write a small program, because that situation is the result of the work of complex application. Rocksdb is only part of it. 

Please look at the LOG file, maybe I forgot to override some default value.

**Comment by dhruba** [comment]
Your LOG file seems ok.

Please see if you can modify https://github.com/facebook/rocksdb/blob/master/examples/simple_example.cc acoriding to the steps you have listed above to reproduce this problem.

**Comment by amostyaev** [comment]
Sorry, I can't reproduce this, Will try to implement workaround to store that value.

**Comment by dhruba** [comment]
No problem, let me know if you run into any other issues.
