### ISSUE TITLE
Question: TablePropertiesCollector zeroing out all seq?

### ISSUE THREAD

**Issue by zergvszerg** [facebook/rocksdb#11103]
We observed seqno of all keys in sst set to zero after setting up a custom SstFileWriter mimicking TablePropertiesCollector, in hope of ingesting normal sst(flushed/compacted by other db instance).

At first glance, rocksdb seem to Write/Get correctly despite all seqno in sst being zeroed out. But is there a pitfall with this approach?

```
class UserTablePropertiesCollector : public rocksdb::TablePropertiesCollector {
  uint32_t version_ = 2;
  uint64_t global_seqno_ = 0;
public:
  rocksdb::Status Finish(rocksdb::UserCollectedProperties* properties) override {
    // File version
    std::string version_val;
    PutFixed32(&version_val, static_cast<uint32_t>(version_));
    properties->insert({"rocksdb.external_sst_file.version", version_val});

    // Global Sequence number
    std::string seqno_val;
    PutFixed64(&seqno_val, static_cast<uint64_t>(global_seqno_));
    properties->insert({"rocksdb.external_sst_file.global_seqno", seqno_val});
    return rocksdb::Status::OK();
  }
};
```

**Comment by zergvszerg** [comment]
a) Does zeroing out seqno break snapshot isolation? Assuming an insertion into memtable after GetSnapshot() which of course get seqno intact, but when the memtable is flushed the seqno gets zeroed and the snapshot suddenly can "see" it?

b) How does the MergingIterator behind DB::NewIterator work with multiple internal keys with the same user key and the same seqno(=global_seqno)?

**Comment by cbi42** [comment]
@zergvszerg RocksDB should only zero out seqno of keys when its safe to do so, and one of the conditions required is that a key needs to have a sequence number below earliest snapshot for its sequence number to be zeroed out during compaction. (this is where seqno zeroing happens: https://github.com/facebook/rocksdb/blob/24ac53d81a2c97f6c30305bd2c3a12f0800ab945/db/compaction/compaction_iterator.cc#L1178-L1231).

> a) Does zeroing out seqno break snapshot isolation? Assuming an insertion into memtable after GetSnapshot() which of course get seqno intact, but when the memtable is flushed the seqno gets zeroed and the snapshot suddenly can "see" it?

This should not happen since the key in memtable has a sequence number newer than snapshot.

> b) How does the MergingIterator behind DB::NewIterator work with multiple internal keys with the same user key and the same seqno(=global_seqno)?

An invariant that RocksDB tries to maintain is that internal keys (user key + seqno + op_type) are distinct. So MergingIterator assumes that this case does not happen.
