### ISSUE TITLE
Maximum RocksDB dataset size?

### ISSUE THREAD

**Issue by javierarilos** [facebook/rocksdb#11241]
Hi there 👋🏼

I tried to google and search in the documentation, without success... I'd really appreciate any input or help on this.

We're in the process of using RocksDB for some big datasets, up something in the order of 10TB. Data is crunched in the background, updated in batches and then it's served to downstream services that do the queries.

Latency on reads is expected to be low (in the order of < 5ms P99).

My question is, for this kind of escenarios, is there a physical or theoretical limit on how much data a single RocksDB instance can serve? How does read latency increase with dataset size? Are those latency requirements reasonable for RocksDB? What should be our dataset limit per instance for meeting them? I'm trying to figure out how to arrange data sharding in different RocksDB instances, if needed.

**Comment by javierarilos** [comment]
Thank you Andrew!
a quick follow up question... as the dataset grows, are increases in read latency expected? I guess compaction is the best cure for that, am I right? 
Any documentation or blogpost on that topic?
Latency wise, our requirement of reads at 5ms P99 is totally OK, correct?

**Comment by ajkr** [comment]
> as the dataset grows, are increases in read latency expected?

Yes, but it can mostly be mitigated. The number of nonempty levels will grow logarithmically with respect to the dataset size. By default (max_bytes_for_level_multiplier=10) an increase in dataset size by 10x will lead to one additional nonempty level. The extra level increases latency because reads have to check levels one by one until they find the lookup key. However, the cost of this extra level can be mostly mitigated by using Bloom filter: https://github.com/facebook/rocksdb/wiki/RocksDB-Bloom-Filter

Besides tuning filters, setting up a block cache (https://github.com/facebook/rocksdb/wiki/Block-Cache) that caches indexes/filters is needed to keep memory usage limited.

For loading 10TB of data, it would be very slow through the live DB write APIs (`Put()`, etc.), so you may wish to use `SstFileWriter`: https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files

**Comment by javierarilos** [comment]
Thank you very much @ajkr !!!!
