### ISSUE TITLE
"No space left on device" when running backup

### ISSUE THREAD

**Issue by theolivenbaum** [facebook/rocksdb#11508]
Just hit a bug in one of our production systems while performing a backup. Database has ~7TB, and was performing an incremental backup to a drive with 15TB, 11TB from previous backups, 4TB free. Incremental backup crashed overnight even though there was still plenty of space available.

### Expected behavior
Incremental backup works as expected.
### Actual behavior
Backup crashed with out of disk space, even though plenty of disk space is available
Message was:
´´´´´
IO error: No space left on device: While fdatasync: /data/private/3/4888577.log: No space left on device
at: rocksdb_backup_engine_create_new_backup_flush(IntPtr be, IntPtr db, Boolean flush_before_backup)
´´´´´
The issue seems similar to #9762, but happened while there was still enough disk space.

Any ideas?

**Comment by jowlyzhang** [comment]
It would be helpful if you can share the rocksdb logs. Just want to make sure I understand this correctly, the drive has 4TB available before the incremental backup started. Out of the databases ~7TB total size, how much of it do you expect needs to be incrementally copied over to the drive. When you say "even though plenty of disk space is available", do you mean you are confident there are less than 4TB of the 7TB that needs to be copied over, or there are space still remaining on the drive after the backup crashed.  If it's the latter, I would assume it's because rocksdb cannot successfully do the full incremental backup, so it backed out, leaving those space still available.
