### ISSUE TITLE
Periodic/TTL compaction too large

### ISSUE THREAD

**Issue by tabokie** [facebook/rocksdb#11502]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Grab files for periodic compaction in small batches (smaller than `max_compaction_bytes`).

### Actual behavior

Compaction as big as 600GB is triggered. During the lifetime of this compaction, all files referenced by its version cannot be deleted. These two factors combined drain the disk space rapidly.

### Steps to reproduce the behavior

It should be reproducible in unit test. We observe this phenomenon in a production server that uses leveled compaction and has 3TB data.

**Comment by tonyxuqqi** [comment]
> @tabokie Are you using universal or leveled compaction?
@cbi42 
leveled compaction.

**Comment by cbi42** [comment]
Hi - I looked at the code for periodic and TTL compaction for leveled compaction. Periodic compaction should be small usually since it compacts a picked file to the same level. For TTL, large compaction most likely happens when an input file spans a very large range (overlapping with a lot of files in output level). Can you check if this is the case? In this case, there is no easy way to split the compaction to smaller batches. Also if it's due to an input file having a large range, the issue is likely not specific to TTL compaction.

**Comment by tabokie** [comment]
@cbi42 You are right. I misread the code. Let me close this for now.
