### ISSUE TITLE
SST file size and read only performance

### ISSUE THREAD

**Issue by patelprateek** [facebook/rocksdb#11628]
Ingesting few hundred GB of data , using only L0 and L1
I am following a bulk load approach where i run a final compaction in the end.
Is there any performance implication when i open the DB in read only mode based on the target_file_size i.e is it advisable to generate large final sorted run files for ex : few 16Gb file vs thousands of 64 Mb files post final compaction. 
If yes , what are the limitations , how large a single SST file can be , i assume for smaller SST file i would run into too many file descriptors and file metadata issues ? 
Can you please advise on ideal target file size following final compaction for optimal read only performance

**Comment by ajkr** [comment]
Our most similar internal user uses 4GB target file size for such compactions. I think the main thing to think about is the metadata blocks: https://github.com/facebook/rocksdb/wiki/Rocksdb-BlockBasedTable-Format#index-block.

For example, index/filter construction during table building uses memory proportional to the file size. Additionally, indexes/filters in block cache that are similar size or larger than a block cache shard can cause thrashing. This can be mitigated to some extent by partitioning.

Another example: if you use dictionary compression, smaller file results in a better dictionary as it has more local/targeted content.

One consideration unrelated to metadata blocks is compaction picking. Since it picks at file granularity, there's more options with smaller files, which might lead to better efficiency. It's less likely nowadays that we have better file cutting heuristics, but still possible.

There's probably more considerations, but I'd suggest trying it out. Typically I'd suggest increasing it until there's a noticeable downside.
