### ISSUE TITLE
Seems BYTES_WRITTEN(rocksdb.bytes.written) is doubled

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#12061]
### Expected behavior
Ticker `rocksdb.bytes.written` should be close to `rocksdb.wal.bytes`.

### Actual behavior
Sometimes Ticker `rocksdb.bytes.written` is consistently about **2x** of `rocksdb.wal.bytes`.

### Steps to reproduce the behavior
MyRocks write.

![image](https://github.com/facebook/rocksdb/assets/1574991/aa9ef2ce-5a01-413b-b18f-6d93738f5408)

**Comment by cbi42** [comment]
Hi, thanks for reporting. You are right, it seems we double count `rocksdb.bytes.written` when not writing to memtables, which happens when using transaction. 
total_byte_size not taking into account `writer->ShouldWriteToMemtable()`:
https://github.com/facebook/rocksdb/blob/2f9ea8193f641c536f4a9ada869611a06708956f/db/db_impl/db_impl_write.cc#L438-L443

WriteImplWALOnly:
https://github.com/facebook/rocksdb/blob/2f9ea8193f641c536f4a9ada869611a06708956f/db/db_impl/db_impl_write.cc#L993

**Comment by kevinmingtarja** [comment]
Hi, I'm interested in taking on this issue.
