### ISSUE TITLE
Question: Why does WAL not support directio? Is this intentionally designed that way?

### ISSUE THREAD

**Issue by zgcbj** [facebook/rocksdb#12136]
Why does WAL not support directio? Is this intentionally designed that way?

**Comment by ltamasi** [comment]
Direct I/O is not a good match for the WAL (or the MANIFEST for that matter) because of the requirements it places on both the in-memory and on-disk addresses. Since you can only write entire (4K-aligned) 4K-sized pages this way, using direct I/O would entail rewriting previous records potentially several times (depending on record size), leading to increased write amp for the WAL (as well as potential corruptions).
