### ISSUE TITLE
EnvDefault/EnvBasicTestWithParam.ReadWrite/0 fails on Windows due to positional read beyond the end of the file

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#1255]
Windows refuses to honor a positional read with an offset that is too big for the given file yet this apparently works for Posix. What is the rationale behind this ?

c:\dev\rocksdb\rocksdb\util\env_basic_test.cc(243): error: Value of: rand_file->Read(1000, 5, &result, scratch).ok()
ARNING:   Actual: false

**Comment by ajkr** [comment]
it became this way because PosixRandomAccessFile::Read() uses pread(2), which succeeds with offset-beyond-EOF, and we use PosixEnv as our gold standard for other Envs. I'm sure we can change this though without breaking anything. But would it be easier to address this in the windows Env by checking offset against file size before invoking the read?

**Comment by yuslepukhin** [comment]
@ajkr True, we can do that. It is more of the question what is the right thing to do.

**Comment by yuslepukhin** [comment]
I think this is fixed now inline with Posix implementation.
