### ISSUE TITLE
Safer shutdown behaviour by deafult

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#12570]
Per the faq: https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ#basic-readwrite

```
Q: Is it safe to close RocksDB while another thread is issuing read, write or manual compaction requests?

A: No. The users of RocksDB need to make sure all functions have finished before they close RocksDB. You can speed up the waiting by calling CancelAllBackgroundWork().
```

Is there a reason why rocksdb doesn't automatically check that all background work is cancelled and if not cancel it when a user calls close?  This is definitely something I didn't know about/expect until I happened to read the FAQ

**Comment by ajkr** [comment]
> Is there a reason why rocksdb doesn't automatically check that all background work is cancelled and if not cancel it when a user calls close?

We do that.

I think the `CancelAllBackgroundWork()` suggestion you quoted is about speeding up the step of "make sure all functions have finished before they close RocksDB". Whether that step is really needed, I don't know. But assuming it is, the purpose of calling a function like `CancelAllBackgroundWork()` would be to make the manual compactions requests finish sooner so that you can call Close().

Maybe the FAQ should suggest calling `DisableManualCompaction()` instead.

**Comment by zaidoon1** [comment]
oh i see, so rocksdb handles canceling/finishing up processing of read/writes automatically, it's mainly the manual compaction part that is the issue which can be taken care of by either `CancelAllBackgroundWork` or `DisableManualCompaction`
