### ISSUE TITLE
Consider fixing benchmark-linux in GitHub Action and re-enable the job

### ISSUE THREAD

**Issue by jaykorean** [facebook/rocksdb#12615]
Due to a Meta internal company-wide decision, we had to migrate from CircleCI to GitHub Actions. We were able to migrate all of the jobs except one, [`benchmark-linux`](https://github.com/facebook/rocksdb/blob/main/.github/workflows/benchmark-linux.yml). As of 05/02/2024, we deactivated all jobs from CircleCI.

Once we fix the job in GHA, we can consider re-enabling it.

Prior PRs for the migration for the reference: https://github.com/facebook/rocksdb/pull/12163, https://github.com/facebook/rocksdb/pull/12569, https://github.com/facebook/rocksdb/pull/12191

**Comment by jaykorean** [comment]
cc @adamretter , @pdillinger , @ajkr

**Comment by jaykorean** [comment]
AWS EC2 instance has been stopped (but not terminated). We can start the instance again when we start running the test again.

**Comment by adamretter** [comment]
@jaykorean Can you keep the instance running, so that we can connect to it, we can then investigate in the next few days if its possible to re-configure it for GitHub actions instead of CircleCI.

**Comment by adamretter** [comment]
@jaykorean You should have access to the Google Doc now. I tried to SSH to the current hostname in there, but there is no access. Would you be able to update the hostname please?

**Comment by jaykorean** [comment]
@adamretter Just updated the Google Doc with the new hostname. Please try it and let me know if there's any problem.

**Comment by adamretter** [comment]
@jaykorean Thanks, got it :-)

**Comment by jaykorean** [comment]
@adamretter Just wanted to let you know that I received the heads up from Danny for the next steps. I will look into them later this month.

**Comment by adamretter** [comment]
@jaykorean Ace. Thanks. I think it should be pretty quick as we just need one thing enabled on your side and then we can continue finalising the config and setup.

**Comment by jaykorean** [comment]
@adamretter You should be able to see the self-hosted runner added here - https://github.com/facebook/rocksdb/actions/runners?tab=self-hosted

**Comment by rhubner** [comment]
Hello @jaykorean 
Thank you for adding the self-hosted runner. Unfortunately we can't see the url you mentioned. I don't have enough permission and last time when we tried with @adamretter he also can't see them. But this shouldn't be a problem.

I can see you configured self hosted Linux machine in AWS, I can see it is connecting to GitHub. Unfortunately when I trigger job, it can't find `benchmark-linux`. I think the problem is that GitHub actions work on _labels_ and not on self hosted runner names. Can you please add label `benchmark-linux` to the self hosted runner in GitHub console(the url you mentioned).

Thanks Radek.

**Comment by adamretter** [comment]
@rhubner I can see the URL now, and it shows the following:
<img width="661" alt="Screenshot 2024-07-25 at 14 16 36" src="https://github.com/user-attachments/assets/de88a9ee-9fef-4054-b7a3-d2f973d6a23f">
