### ISSUE TITLE
Best way to delete everything from column family

### ISSUE THREAD

**Issue by brigadier** [facebook/rocksdb#1295]
Hi,
what is the fastest way to delete all keys from column family? Is sequence of `DropColumnFamily(); CreateColumnFamily();` enough fast (preferable constant time) and does it guarantee that no keys from the given column family would exist after column family with the same name is reopened?

I need to do this once a day - clear about 30 column families from about 30 threads, in the same time with minimal delay.

**Comment by igorcanadi** [comment]
Yes, DropColumnFamily()/CreateColumnFamily() are constant time. I'm also 99% sure that you can create the column family with the same name as the previously dropped one. Internally we use IDs instead of names and the new column family would get the new ID, so there's no risk of mixing the old and new column family data.

**Comment by yhchiang** [comment]
If you don't want anything stored in that column family, then DropColumnFamily() is the best way.

**Comment by VladRodionov** [comment]
Couple more questions:

* dropped cf will no longer be accessible, does db drops memtables for this cf as well?
* Is continuous dropping/creating CFs normal scenario for a live db? 
* can db support 100s of CF?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by socketpair** [comment]
Well, Will it work if parallel readers exists? Assume they call `TryCatchUpWithPrimary()` time-to-time.
