### ISSUE TITLE
Database corrupted after crash

### ISSUE THREAD

**Issue by alexreg** [facebook/rocksdb#1554]
My program crashed, and it seems the database is now corrupted! Next time I try to open it, I get an error:

```
/var/local/foo-db/MANIFEST-000008: No such file or directory
```

What's going on here? How do I recover from this crash?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by alexreg** [comment]
Huh? It's up to you to investigate now! You can't call this abandoned if you haven't even tried to investigate. That's your problem.

**Comment by gfosco** [comment]
Hi Alex,

Unfortunately, this issue is from over a year ago, and includes no information anyone could use to investigate.  Not a version number, or any logs.  No one else joined your issue, and it was never updated.  Considering those things, this isn't something we should spend time on.

The project had over 400 issues, some over 2 years old.  I'm making an effort to reduce old activity so we can properly focus on recent issues which are more likely to exist in the current version.  The hope is that we stay on top of everything, never letting an issue get old.

Thanks and have a great day,

Fosco

**Comment by alexreg** [comment]
Well, you could have at least requested more information... (by you, I mean the official support/development team). Logs? None, there was just the error. Version number? It was the latest release at the time, though I have no idea now.

Up to you, whether you choose to investigate them, but I personally think it's a bad approach to software engineering...

**Comment by siying** [comment]
Next time it happens, please list all the files under your DB directory.

Another question, do you set "max_manifest_file_size"?

**Comment by alexreg** [comment]
Okay, will do! And no, I didn't set that property, I believe...
