### ISSUE TITLE
Mutex contention from MultiGet

### ISSUE THREAD

**Issue by mdcallag** [facebook/rocksdb#1811]
MultiGet locks DBImpl::mutex_ twice. Get locks it directly zero times. mutex_ is highly contended so this means more mutex contention.

MultiGet: https://github.com/facebook/rocksdb/blob/master/db/db_impl.cc#L4060
Get: https://github.com/facebook/rocksdb/blob/master/db/db_impl.cc#L3994

The problem should be worse with more than 1 column family but I did not test that.

Reproduction case is:
./db_bench --db=rdb --benchmarks=overwrite --num=100000000

# too much mutex contention
for t in 1 2 4 8 12 16 20 24 28 32 36 40 ; do echo $t; ./db_bench --batch_size=1 --db=rdb --use_existing_db=1 --num=100000000 --reads=$(( 50000 * $t * 8 )) --benchmarks=multireadrandom --threads=$t >& o3.$t; done

# less mutex contention
for t in 1 2 4 8 12 16 20 24 28 32 36 40 44 48 ; do echo $t; ./db_bench.t0  --db=rdb --use_existing_db=1 --num=100000000 --reads=$(( 20000 * $t * 20 )) --benchmarks=readrandom --threads=$t >& o2.$t; done

Test server has 48 cores with HT enabled.

The data below have 3 columns: <#clients> <avg QPS> <QPS / client>. 

The QPS per client for MultiGet up to 28 clients. Wasn't willing to wait for the rest. QPS drops dramatically even before there is one client per real core.
```
# for t in 1 2 4 8 12 16 20 24 28 32 36 40 44 48 ; do tail -1 o3.$t | awk '{ printf "%s\t%s\t%.0f\n", t, $5, $5 / t }' t=$t ; done
1       142066  142066
2       256976  128488
4       490531  122633
8       870671  108834
12      969779  80815
16      966410  60401
20      929902  46495
24      921192  38383
28      926523  33090
```

The QPS per client for Get is almost flat until the number of clients exceeds the number of real CPU cores. Given that all data is in memory (all in OS page cache, not all in block cache), this is good.
```
# for t in 1 2 4 8 12 16 20 24 28 32 36 40 44 48 ; do grep readrandom o2.$t | tail -1  | awk '{ printf "%s\t%s\t%.0f\n", t, $5, $5 / t }' t=$t ; done
1       148072  148072
2       273875  136938
4       526818  131704
8       1039728 129966
12      1509442 125787
16      2012579 125786
20      2421309 121065
24      2821905 117579
28      2860780 102171
32      2970298 92822
36      3226163 89616
40      3361579 84039
44      3476910 79021
48      3635383 75737
```

**Comment by siying** [comment]
I had a brief comment in internal discussion saying we don't need the mutex in MultiGet() case. However, I rethink about it more and realized that removing this mutex in MultiGet() for multiple column families is not very trivial. The reason is that, we need to make sure the sequence number we are going to use for this MultiPut will be a logical snapshot available. For example:
```
thread 1: Put(CF1, 'foo', 'v1')
thread 1: Put(CF2, 'bar', 'v1')
               (position 1)
thread 1: Put(CF2, 'bar', 'v2')                
thread 1: Delete(CF1, 'foo');
               (position 2)
thread 2: MultiGet([(CF1, 'foo'), (CF2, 'bar')])
```
We don't want the result to be:
```
(CF1, 'foo') => not existing
(CF2, 'bar') => 'v1'
```
This can happen if we get the sequence number for the query in (position 1), and in (position2), a flush to CF1 happens, which removes the 'foo'->'v1' entry, and we grab the LSM-tree for CF1 after that.

Now, this is prevented by acquiring a mutex, grabbing a sequence number, pinning down all the current SST files and memtables. It is not easy to do it without acquiring a mutex. We can implement it by declaring a formal snapshot, which will prevent flush/compaction from removing the data we want, but declaring and removing snapshot is also within the mutex. Maybe by holding it shorter the scalability can be much better. We can give it a try.

By the way, I realized there may be a bug in the current Get() code too, which can cause wrong empty results returned in theory. Maybe we should fix this.

**Comment by siying** [comment]
I can reproduce the Get() bug I mentioned with this simple unit test: https://github.com/facebook/rocksdb/pull/1813

**Comment by siying** [comment]
Two ideas I can think of:
(1) we have a super super version that reference the super versions of all the column families. Every time a super version is updated for any CF, we update the super super version. So referencing the super super version can be atomic without mutex. This is hard to implement
(2) a brute force way: we reference all the super versions, and see whether the current snapshot can be satisfied by all the CFs. If it can (should be the common case), then we go ahead without taking the mutex. If we can't, we fall back to the current way.

**Comment by siying** [comment]
Anyone from the community is interested in contributing to this?

**Comment by mritun** [comment]
siying@ Both the suggestions are essentially implementing an optimistic lock instead of (currently) pessimistic lock?

**Comment by siying** [comment]
@mritun the first suggestion is not. This is to replace locking by one reference counting.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by gfosco** [comment]
Re-opened per Mark.

**Comment by siying** [comment]
@ajkr is working on it.

**Comment by mdcallag** [comment]
I am unable to reproduce this using v6.0.2 up to v6.26.1 with test scripts [from here](https://github.com/mdcallag/rocksdb/tree/main/me/b1811)
