### ISSUE TITLE
Notification callbacks (event callbacks)

### ISSUE THREAD

**Issue by sledgeh** [facebook/rocksdb#1846]
Hello tech-people. I am looking for database ability *notify me when value updated/changed*.
Here is my view of interface/usage pseudo-code:
```
db.addEvent("keyname", EventType::UPDATE, [](newVal){cout<<newVal;} );
db.addEvent("keyname", EventType::UPDATE, [](newVal,changerDbConnectionId){cout<<newVal;} );
```
SQLite has [Data Change Notification Callbacks](https://sqlite.org/c3ref/update_hook.html)

If there is now such feature, I would like to implement / participate in implementation. So any help is welcome.

**Comment by IslamAbdelRahman** [comment]
RocksDB write path cannot differentiate between Insert/Update. because on the write path we don't know if the key exists or not in the DB.

but you can implement a way to add a hook when Put/Delete is called to notify you when a specific key is Put/Delete, but this can also be done in the application layer

**Comment by hocngo** [comment]
Sledgeh: Are you going to implement this feature?

**Comment by sledgeh** [comment]
not in nearest future.
