### ISSUE TITLE
Questions about using RocksDB on top of distributed file system.

### ISSUE THREAD

**Issue by ufosaga** [facebook/rocksdb#1880]
Hi, 

I am thinking building a data center using RocksDB as the storge engine.
I prefer to use a distrubuted file system(e.g. GlusterFS) to store the data.

The RocksDB client will manipulate database on pre-mounted remote path e.g.:

/mnt/glusterfs/

Questions:
1. Is this design feasible?
2. Can RocksDB sustain single database size which might be larger than xxx TB or xx PB? 
3. What is the theoretical limit to a single RocksDB storage? I know it depends on the host capability, say we are using a server that has 1 PB disk and 512GB ram.

**Comment by baotiao** [comment]
It is not appropriate to use a distributed file system to store RocksDB's Data.
RocksDB is designed as a lsm-tree. The main advantage of lsm-tree is that it transform the random write to disk to sequential write. Since in physical disk, sequential write is about 100 times fast than random write. However, as I know many distributed file system don't have this advantage. Indeed, distribute file system such ceph has a faster random write than sequential write. So, I think it is not appropriate to use a distributed file system to sotre RocksDB's Data.

We have single database about 800GB in out pcie card machine, we haven't test more than this size.

**Comment by siddontang** [comment]
I guess the latter blob storage support can satisfy your need.

**Comment by ajkr** [comment]
2. There will be some perf degradation once filter+index blocks can no longer fit in memory (cc @maysamyabandeh who's working on this problem). Also, depending on how quickly your data changes, you may be CPU-bound by compression/merging during flush/compaction.

**Comment by mdcallag** [comment]
This looks interesting - https://github.com/rockset/rocksdb-cloud and https://www.percona.com/live/17/sessions/rocksdb-cloud

**Comment by siying** [comment]
Storing data on a distributed file system should be feasible. You are welcome to report the problem you saw.

Usually single RocksDB is under 1TB. Is there any reason you want a much larger RocksDB instance?

**Comment by rockeet** [comment]
We have a single RocksDB with more than 4TB data.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by bramaswamy** [comment]
Hi,

Can we run RocksDB on a share Azure file system

Getting the below error

Exception in thread “main” org.rocksdb.RocksDBException: While fsync: a directory: Invalid argument
at org.rocksdb.RocksDB.open(Native Method)
at org.rocksdb.RocksDB.open(RocksDB.java:286)
at com.dremio.datastore.ByteStoreManager.openDB(ByteStoreManager.java:173)
at com.dremio.datastore.ByteStoreManager.start(ByteStoreManager.java:148)
at com.dremio.datastore.CoreStoreProviderImpl.start(CoreStoreProviderImpl.java:167)
at com.dremio.datastore.LocalKVStoreProvider.start(LocalKVStoreProvider.java:88)

Thanks
