### ISSUE TITLE
Make failed -- ld: library not found for -lrt

### ISSUE THREAD

**Issue by xiusir** [facebook/rocksdb#1934]
And I have installed gflags-2.2.0 using brew install.
I googled "osx librt"  - somebody said that "OSX don't support librt, use libSystemV.B instead "?

#mkdir build && cd build
#ccmake ..
#make 
...
[ 96%] Building CXX object CMakeFiles/rocksdb-shared.dir/port/port_posix.cc.o
[100%] Building CXX object CMakeFiles/rocksdb-shared.dir/util/env_posix.cc.o
[100%] Building CXX object CMakeFiles/rocksdb-shared.dir/util/io_posix.cc.o
[100%] Linking CXX shared library librocksdb.dylib
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [librocksdb.5.2.0.dylib] Error 1
make[2]: *** [CMakeFiles/rocksdb-shared.dir/all] Error 2
make[1]: *** [CMakeFiles/dynamic_bloom_test.dir/rule] Error 2
make: *** [dynamic_bloom_test] Error 2

#gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by yiwu-arbug** [comment]
The CMake script probably don't support OSX. Can you try `make` instead?

**Comment by zedware** [comment]
Encountered the same problem.

**Comment by zedware** [comment]
make will see an error,

table/partitioned_filter_block_test.cc:59:22: error: no matching function for call to 'max'
      max_key_size = std::max(max_key_size, keys[i].size());
                     ^~~~~~~~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:2654:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('unsigned long long' vs. 'unsigned long')
max(const _Tp& __a, const _Tp& __b)
^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:2664:1: note: candidate template ignored: could not match 'initializer_list<type-parameter-0-0>' against 'unsigned long long'
max(initializer_list<_Tp> __t, _Compare __comp)
^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:2646:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:2672:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
max(initializer_list<_Tp> __t)
^
1 error generated.
make: *** [table/partitioned_filter_block_test.o] Error 1

And the fix is:
diff --git a/table/partitioned_filter_block_test.cc b/table/partitioned_filter_block_test.cc
index 3f320d4..e631fd8 100644
--- a/table/partitioned_filter_block_test.cc
+++ b/table/partitioned_filter_block_test.cc
@@ -56,7 +56,7 @@ class PartitionedFilterBlockTest : public testing::Test {
     int num_keys = sizeof(keys) / sizeof(*keys);
     uint64_t max_key_size = 0;
     for (int i = 1; i < num_keys; i++) {
-      max_key_size = std::max(max_key_size, keys[i].size());
+      max_key_size = std::max(max_key_size, (uint64_t) keys[i].size());
     }
     uint64_t max_index_size = num_keys * (max_key_size + 8 /*handle*/);
     return max_index_size;

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
