### ISSUE TITLE
heavy write load is unstable

### ISSUE THREAD

**Issue by oranagra** [facebook/rocksdb#2005]
Hi,
I have a problem with heavy write load in which the throughput jumps from about 80,000 writes per seconds, down to some 300 writes per seconds and then back up.
these peaks repeat themselves about once or twice a second.
looking at the recent change log i saw `Improve Write Stalling System` (cd7c4143d795ab9a53e6eaeb4ee572b4e258313b) which was suppose to improve that situation, but i don't see that it did in my case.

tested on EC2 i3.8xlarage with RAID0 of 4 NVMe drives.
i should note that i'm enabling **use_direct_writes** (v5.1.5) so that the writes go the the disk and don't aggregate in the OS page cache (see note below).
i saw this behavior in v4.9 and v5.0.2, too, where i used allow_os_buffer=false.

i'm attaching a small sample application that reproduces the problem, and the output i got.
it attempts to print the average ops/sec every 250ms.
[simple_example.cc.txt](https://github.com/facebook/rocksdb/files/854896/simple_example.cc.txt)
[output.txt](https://github.com/facebook/rocksdb/files/854897/output.txt)

i attempted to tweak many of the parameters such as level0_slowdown_writes_trigger etc, but i didn't succeed in solving the problem.
please tell me if there's some configuration change that i can do to improve, or if you see some problem with rocksdb implementation that can be fixed.

note: one of the reasons i use direct writes (or allow_os_buffer=false) is because i'm doing my tests and experiments on a very powerful machine that is currently mostly empty, and i don't want to see false benchmark due to the fact everything goes to the RAM, and then when the real application will use all the RAM of the machine, the performance will drop (when it will really become disk-bound)

**Comment by oranagra** [comment]
@siying maybe you can take a look (seems to be related to the write stalling system which you recently improved).
thanks.

**Comment by siying** [comment]
Is it a problem because you cannot reach the write throughput you want, or because the latency is too high while a stalling is triggered?

**Comment by siying** [comment]
Is it possible to share your LOG file after the run?

**Comment by oranagra** [comment]
i don't have a target write throughput in mind.. i want the fastest i can get.
but i would like the throughput to be smooth and not jaggy.
ideally the throttling mechanism should slow down the intake to the sustainable speed of the disk.
but what happens now is that it keeps jumping between very high throughput and very low throughput.

i can reproduce and upload the log file... 
but it is also easy to run the attached example application that reproduces it and emits a pseudo throughput graph. (just modify the path at the beginning, compile and run)

**Comment by oranagra** [comment]
@siying here's a debug log.
[var_opt_redislabs_flash_rocksdb_test_LOG.zip](https://github.com/facebook/rocksdb/files/856037/var_opt_redislabs_flash_rocksdb_test_LOG.zip)

again, this is a 30 second test that is very easy to run to reproduce the problem (and test theories)

**Comment by siying** [comment]
@oranagra in your specific case, you should increase Options.delayed_write_rate to much higher than 2MB/s. Set it 32MB/s or larger.

You are inserting keys in mostly sorted order (but not). It's very interesting. Is it close to your user case?

**Comment by oranagra** [comment]
@siying thanks for your help.
i just tried increasing compaction readahead to 32 and 64mb, it doesn't seem to change anything.
it still juggles between 300 and 70k ops/sec, and the average throughput at the end is still about 20-23k ops/sec.

anyway, although i would love to improve the compaction speed, and overall throughput, the issue here is the fact that it seems to constantly switch between extreme slowdown and full speed (which just goes into ram, causing it to go to extreme slowdown again).
i tried playing with level0_slowdown_writes_trigger, delayed_write_rate, soft_pending_compaction_bytes_limit etc, and couldn't find something to solve that.
in addition to that, my software is suppose to run on all kinds of platforms and handle all kinds of workloads, i can't afford to tune these to a specific workload / disk speed.
this is why the automatic adaptive mechanism (and your recent improvements) look very appealing.

regarding the key names, this is just a test i wrote to reproduce the problem so that it is easier to investigate. i don't actually know anything about the insertion order that will be used by the actual product.

**Comment by siying** [comment]
@oranagra a much larger delayed_write_rate will get you the throttling rate of much higher than 300. It's hard to get RocksDB to be extremely smooth but 300 probably can be avoided.

I suggest you run with level0_slowdown_writes_trigger=10 and level0_stop_writes_trigger to be 36 (the idea is that the gap of the two is high), with delayed_write_rate to be as high as 32MB.

If I understand correctly, in your benchmark, each value size is about 6KB. 300 op/s each 6KB is 1.8MB/s. The number itself is not low itself. And the reason it is 1.8MB/s is that the default delayed_write_rate is 2MB/s.

I'm asking your pattern because, the workload you generated is almost sequential so that you are expected to get much better throughput than random workload. If you want to test worst case write throughput, I suggest you to generate keys in totally random order, and then you'll see a more unfriendly results. In that scenario, the throttled rate (the one given by delayed_write_rate) of megabytes per second may not be too low.

**Comment by oranagra** [comment]
@siying thanks for your help.
with some changes in the direction you suggested (delayed_write_rate of 64mb), i'm able to get the fluctuation to be between 30k and 10k. this 3x fluctuation is still high, but a big improvement from 200x fluctuation of i had before.

looking at the commit comment of https://github.com/facebook/rocksdb/commit/cd7c4143d795ab9a53e6eaeb4ee572b4e258313b i was under the impression that under a constant load, the new mechanism will find the sweet spot automatically, but if you're saying that "It's hard to get RocksDB to be extremely smooth", then i'll take your word for it.

if you think i can still get it better, please let me know.
thanks.

**Comment by siying** [comment]
@oranagra RocksDB will try to reach a sweet spot for the throttling rate. The throttling rate will always start since level0_slowdown_writes_trigger triggers. It means before this number, you'll see higher insert rate, and after that, it will be limited to a limited rate. So unfortunately, so far the fluctuation you mentioned is hard to avoid.

**Comment by loadwiki** [comment]
Hello guys！I have the similar situation. In my case log data is written to rocksdb,pure write no read.
My case:  key 32bytes,value 256 bytes; all k,v is random generated.
                 tps range:top 50k, low 8000,
                 write_buffer_size=128m,max_write_buffer_number=5
                 level0_slowdown_writes_trigger=default,delayed_write_rate=default
My target is a max smooth pure write rate.Is there some parameter of rocksdb can be tuned?
It seems that the default rocksdb parameter couldn't get a smooth write rate, while the gap may be more than 100 times.

**Comment by loadwiki** [comment]
@siying Following your suggestion above with smaller  level0_slowdown_writes_trigger bigger delayed_write_rate, either the overall write rate or the stability of write speed are not convenient.
Here is some conf and log info:
write_buffer_size=128m,max_write_buffer_number=5
level0_slowdown_writes_trigger=6,delayed_write_rate=64,
server config: 32 core 128G 4T sata disk
2017/11/22-20:14:37.197649 7fc295bfd700 [WARN] [default] Stalling writes because we have 17 level-0 files rate 17903900
2017/11/22-20:14:42.681627 7fc28cbff700 [WARN] [default] Stalling writes because we have 17 level-0 files rate 14323120
2017/11/22-20:14:43.816929 7fc2577ff700 [WARN] [default] Stalling writes because we have 18 level-0 files rate 11458496
2017/11/22-20:14:50.804405 7fc27a7ff700 [WARN] [default] Stalling writes because we have 18 level-0 files rate 9166796
2017/11/22-20:14:50.964117 7fc23a7ff700 [WARN] [default] Stalling writes because we have 18 level-0 files rate 11458495
2017/11/22-20:14:59.502865 7fc2907ff700 [WARN] [default] Stalling writes because we have 18 level-0 files rate 9166796
2017/11/22-20:15:01.021685 7fc2577ff700 [WARN] [default] Stalling writes because we have 19 level-0 files rate 7333436
2017/11/22-20:15:11.696665 7fc2373ff700 [WARN] [default] Stalling writes because we have 19 level-0 files rate 5866748
2017/11/22-20:15:27.605770 7fc239ffe700 [WARN] [default] Stalling writes because we have 19 level-0 files rate 4693398
2017/11/22-20:15:28.993387 7fc2577ff700 [WARN] [default] Stalling writes because we have 20 level-0 files rate 3754718
If L0 file sum is low we can get a speed more than 64M. But if the sum got bigger, the write rate descreses very fast to 3M. Low speed situation lasted more than 10 seconds with write rate less than 10M. 
I've tried universal compact style which is less stability than level based compact.
I've tried FiFo compact style,too. The speed is steady and very high. However, the limit is the write table size.

**Comment by siying** [comment]
@loadwiki if you are dealing with write burst, you can increase level0_slowdown_writes_trigger to much larger, with level_stop_writes_trigger to be even larger. Now the default I believe is something like 32.

**Comment by siying** [comment]
I don't think keeping the issue open can help anything. We don't have any near term improvements planned to help with issue. In long term, we do plan to get a more adaptive LSM-tree setting so that things can be adjusted more dynamically.
