### ISSUE TITLE
Doubts about dropColumnFamily and compaction-filter to some prefix in a single cf

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#2092]
If I use a single column family, I can use different prefixes to group data in the continous sst files. So I can use a compaction-filter to delete the data related.
I can either put data with the same prefix into different column families. And use dropColumnFamily to delete the data related.
I knew that a compaction-filter has to visit every key to filter. But I don't know if physical deletion to a dropped column family is similar or not.  Straight forward physical deletion of the files may be the most efficient but I dont know if rocks really did so.

My question is
a: where is the code(filename:line) that really implements the physical deletion to a dropped cf
b: Is deletion to a cf more efficient than compaction-filter to some prefix in a single column family?

Hoping for your reply, thanks.

**Comment by yiwu-arbug** [comment]
Compaction filter will visit every key to filter, but on compaction we are visiting them anyway. Dropping column family will remove the SST files of the column family, thus don't need to visit the keys again. You can dig into DBImpl::DropColumnfamily() in db/db_impl.cc. However having too many column families (>100 probably) might be problematic (you need to test it out). A third approach is to use RangeDelete(). It is like having compaction filter, but also immediately remove the keys from reads (rather than have to wait for compaction happen). But it also have the caveat where having too many range tombstone in the db will downgrade performance.

**Comment by wolfkdy** [comment]
Thanks, 
```
Dropping column family will remove the SST files of the column family
```
So dropping a column family won't guarentee the semantic of "snapshot isolation" because a snapshot read followed by a immediate dropColumnFamily can read nothing.
am i right?

**Comment by yiwu-arbug** [comment]
I'm not familiar with snapshot. Probably someone else can answer the question. cc @siying @IslamAbdelRahman

**Comment by siying** [comment]
@wolfkdy all the files are still there if you dropped a column family but you still keep a column family handle. Files are actually dropped when you destroyed the handled. Without a handle, you won't have a way to query the data there anyway, so the snapshot problem is not applicable.

**Comment by wolfkdy** [comment]
@siying @yiwu-arbug 
Thanks, I almost got it. With your explaination, it will be easier to understand the code.
I'm from tencent and we are using mongorocks to store PB-level cold data.
Sincerely thanks to you and I'm sure things will continue.
Keep in touch.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
