### ISSUE TITLE
How config Options to support shared block cache in RocksJava api

### ISSUE THREAD

**Issue by clark010** [facebook/rocksdb#2192]
In C++ api, we can use

> std::shared_ptr<Cache> cache = NewLRUCache(capacity);
BlockBasedTableOptions table_options;
table_options.block_cache = cache;
Options options;
options.table_factory.reset(new BlockBasedTableFactory(table_options));

but i can not find the similar api in RocksJava, if there's plan to support this api 
or if there is some other method to do this?

**Comment by lightmark** [comment]
@adamretter

**Comment by adamretter** [comment]
@clark010 At the moment this is not possible in the API. No particular reason as far as I can see. The way that TableOptions in the Java API were implemented previously is perhaps a little strange but I think it was likely done, so that the options are kept on the Java side and only sent to C++ when a new TableFactory is created. This might need a little bit of revision.

We would like to see this supported in the Java API but there is no plan for it at the moment, is this something you would like to send a PR for?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by apete** [comment]
Isn't it time to fix this?

I would guess most developers use RocksDB via the Java API:

1) An important feature like this should be available via the Java API.
2) If the Java and C++ API:s are that different they should be documented separately.

I assume it is still not possible to have a common block cache (any way)? At one point I was hoping that simply creating 2 RocksDB instances using the same `Options` instance would do to the trick:
```
Options options = new Options();

long blockCacheSizeMB = 1024L;
options.optimizeForPointLookup(blockCacheSizeMB);

RocksDB db1 = RocksDB.open(options, "path1");
RocksDB db2 = RocksDB.open(options, "path2");
```
As far as I can see this gives me 2 databases with separate block caches each of 1G.
