### ISSUE TITLE
UnsatisfiedLinkError when using BloomFilter

### ISSUE THREAD

**Issue by bharatviswa504** [facebook/rocksdb#2288]
```
  java.lang.UnsatisfiedLinkError: org.rocksdb.BloomFilter.createNewBloomFilter(IZ)J
        at org.rocksdb.BloomFilter.createNewBloomFilter(Native Method)
        at org.rocksdb.BloomFilter.<init>(BloomFilter.java:74)
        at org.rocksdb.BloomFilter.<init>(BloomFilter.java:51)
```
When using below code, getting a stacktrace error `Unsatisfied linker error`:
```
final BlockBasedTableConfig tableConfig = new BlockBasedTableConfig();
tableConfig.setFilter(new BloomFilter(10));
```

**Comment by bharatviswa504** [comment]
Could you any help me is this issue got fixed or anything wrong in above piece of code?

**Comment by adamretter** [comment]
@bharatviswa504 Can you please tell me which version of RocksDB and which platform?

**Comment by bharatviswa504** [comment]
@adamretter RocksDb version is 5.3.4 and both on mac os and linux I have seen this issue.

**Comment by adamretter** [comment]
@bharatviswa504 Okay so I think it is likely you are misusing the API by accident.

The following code will give the error you are seeing:
```java
import org.rocksdb.BlockBasedTableConfig;
import org.rocksdb.BloomFilter;

public class Test1 {
    public static void main(final String[] args) {
        final BlockBasedTableConfig tableConfig = new BlockBasedTableConfig();
        tableConfig.setFilter(new BloomFilter(10));
    }
}
```

The reason it does so is that the Native library for RocksDB has not yet been loaded. That typically happens when one of the `Options`, `ColumnFamilyOptions` or RocksDB classes are used. As that is  normally the first class that you would use it isn't normally a problem.

If you want the above code to work without needing to depend on those classes you can do this instead:
```java
import org.rocksdb.BlockBasedTableConfig;
import org.rocksdb.BloomFilter;
import org.rocksdb.Options;
import org.rocksdb.RocksDB;

public class Test2 {
    static {
        RocksDB.loadLibrary();
    }

    public static void main(final String[] args) {
        final BlockBasedTableConfig tableConfig = new BlockBasedTableConfig();
        tableConfig.setFilter(new BloomFilter(10));
    }
}
```

**Comment by bharatviswa504** [comment]
@adamretter Thank you. It is working now with given suggestion.
