### ISSUE TITLE
repair problems with WAL and Column Family

### ISSUE THREAD

**Issue by allenlz** [facebook/rocksdb#236]

**Comment by allenlz** [comment]
Rocksdb released to 3.11. Great work. And I found a new wiki page about the Repairer: https://github.com/facebook/rocksdb/wiki/RocksDB-Repairer
Does rocksdb support to reconstruct DB with more than one column family right now?
Thanks.

**Comment by igorcanadi** [comment]
Unfortunately we still don't support repairing DB with more than one column family :(

**Comment by adamretter** [comment]
@igorcanadi Is this a planned feature, can it be added?

**Comment by igorcanadi** [comment]
@adamretter not at this point. the problem is that sst files don't have information about which column family they belong to -- the only information about that is in the MANIFEST. So if the MANIFEST is gone, we have no idea where to put those files.

Do you have a legitimate use-case for DB::Repair()? There are two reasons why we're not very exicted about supporting this:
* Last time we encountered problems with MANIFEST corruption in FB was over a year ago and it was very isolated (I think on one host). It was due to not fsyncing the directory after creating MANIFEST, which is now fixed.
* If your MANIFEST is gone, there is no way to guarantee consistency of any sort. We will pick up any sst files in the directory, but there might be some obsolete files which shouldn't be part of the database.
