### ISSUE TITLE
poor fillrandom performance w/ direct IO

### ISSUE THREAD

**Issue by zhouyuan** [facebook/rocksdb#2515]
Hi RocksDB developers, 

I'm doing some fill random performance testing with  Direct_IO mode.  The performance looks like lower than the buffered IO, and the latency is also much higher. Are there any tunings I missed for the direct IO mode?

| base | use_direct_io_for_flush_and_compaction | 
|------|----------------------------------------------|
|fillrandom   :      97.870 micros/op 10217 ops/sec;   20.1 MB/s| fillrandom   :     308.185 micros/op 3244 ops/sec;    6.4 MB/s|

Here's the db_bench command I'm using

`dir=/fast/rocks; r=12800000; wnum=12800000; t=1; bpl=536870912;mcz=2;del=300000000;levels=6; ctrig=8; delay=32; stop=64; wbn=32; mbc=31; mb=1048576000; wbs=1048576000; sync=1; vs=2048; bs=65536; cs=1048576; of=500000; ./db_bench -use_direct_io_for_flush_and_compaction --benchmarks=fillrandom --disable_seek_compaction=1 --mmap_read=0 --statistics=1 --histogram=1 --writes=$wnum --num=$r --threads=$t --value_size=$vs --block_size=$bs --cache_size=$cs --bloom_bits=10 --cache_numshardbits=4 --open_files=$of --verify_checksum=1 --db=$dir --sync=$sync --disable_wal=0 --compression_type=none --compression_ratio=0.5 --write_buffer_size=$wbs --target_file_size_base=$mb --max_write_buffer_number=$wbn --max_background_compactions=$mbc --level0_file_num_compaction_trigger=$ctrig --level0_slowdown_writes_trigger=$delay --level0_stop_writes_trigger=$stop --num_levels=$levels --delete_obsolete_files_period_micros=$del --min_level_to_compress=$mcz --max_bytes_for_level_base=$bpl --use_existing_db=0`

Below is my testing platform

- ubuntu 16.04
- gcc/g++ 5.4
- Rocksdb a472c4a

thanks, -yuan

**Comment by siying** [comment]
Though the performance comparison between direct I/O and non-direct I/O depend on platform and workload, we are happy to look into your case. Can you provide your LOG file under the DB directory?

**Comment by PraveenSinghRao** [comment]
You might like to check writable_file_max_buffer_size setting - that is the amount buffered in memory before it is written via direct I/O. If that is 0 or too-small, many small writes would be done to disk tanking the perf. The default seems to be 1 MB though which should be more than enough. You can try something like 64kb to see if that works better for your platform.

**Comment by zhouyuan** [comment]
Hi @siying here are the LOGs for direct vs buffered io. IMO direct IO should be better for SSD cases. 

[LOG.use_direct_io.txt](https://github.com/facebook/rocksdb/files/1115468/LOG.use_direct_io.txt)
[LOG.buffered_io.txt](https://github.com/facebook/rocksdb/files/1115469/LOG.buffered_io.txt)

@PraveenSinghRao thanks for the tip! I tried to set `writable_file_max_buffer_size ` to 65536 and the performance improved to 13.9 MB/s here. Will try more tunings on flush & compaction side.

**Comment by siying** [comment]
@zhouyuan I'm very confused. There isn't a write throttling triggered, so the speed is just be as fast as what you can insert to the memtable, which shouldn't change because of this parameter. In fact, the single compaction speed is actually faster in the direct I/O case (search "MB/sec" in both of the two log files). But you do flush much less frequently in the Direct I/O case. I don't understand why.

The `writable_file_max_buffer_size` result doesn't make sense to me. To me, in order to get better results, you should increase the number, rather than reduce it.

I'm running the exact test on my host and see whether I can reproduce your results.

**Comment by siying** [comment]
Oh I realized you are doing --sync which syncs WAL. Then it makes sense to reduce `writable_file_max_buffer_size` to be smaller to avoid large I/O to block the I/O queue. Then setting it to 64KB may make sense. Maybe it can be slightly higher, to 256KB or something. You may consider to reduce `compaction_readahead_size` to slower either, to something like 256KB.

CC @lightmark

**Comment by siying** [comment]
I'm also realizing that you are using one thread to do the write. If you are doing WAL sync write, higher number of threads can trigger group commit, so you may get higher random write throughput.

**Comment by siying** [comment]
@zhouyuan what kind of SSD do you use? A PCI-e card? SATA SSD? Or remote flash like EBS?

**Comment by siying** [comment]
I ran the exactly same test on my host (with PCI-e flash card), and I saw 12% lower throughput with direct I/O option, which is reasonable to me. The direct I/O feature is not meant to always improve performance, but to give people more control of memory usage or I/O size. Since we don't use OS page cache in the direct I/O case, it is very likely that the performance is worse. But we use less resource too. So I'm not worried if the performance is worse. Just pick what fits for you.

**Comment by zhouyuan** [comment]
@siying my bad for the confusion and much appreciated for looking into this! I'm actually testing with one NVMe SSD, and the workload here is extracted from some small application, which will insert small KV pair heavily with a single thread. Thanks for the tips on `compaction_readahead_size `, I also find one useful turning on `subcompactions` from [here](https://github.com/facebook/rocksdb/wiki/Leveled-Compaction). With these two turnings the performance can go to ~21MB/s, should be enough for my goal now. Thanks for education! -yuan

**Comment by zhouyuan** [comment]
closing here as proper turnings are able to bring the direct I/O performance back.
