### ISSUE TITLE
L0->L0 Compaction procedure question

### ISSUE THREAD

**Issue by hshs1103** [facebook/rocksdb#2830]
Hi dear all, 

Recently, I read 'Level-based Compaction Changes post' which was posted June 26, 2017.

In that post, you said that L0->L0 compaction can reduce L0 files. 

I want to know how L0->L0 compaction works. 

I have three questions.

For example, In post's case, 

![l1-l2-contend](https://user-images.githubusercontent.com/20452176/30018912-b2a99432-9199-11e7-83b8-f75cf869b4c5.png)

 

1. Is it a process to create a single large SST file by merge sorting files which are in surrounded by dotted lines?(If you have illustrate about L0->L0 compaction process,  can you illustrate it as simple as possible?)

2. Can you tell me the file and location of the L0->L0 compaction?

Please help me.

**Comment by ajkr** [comment]
Q1: Yes, the dotted lines surround the input files for a compaction, and L0->L0 outputs a single large file. In that illustration there are two parallel compactions -- an L0->L0 taking all the files in L0, and an L1->L2 taking one L1 file and three L2 files. The L1->L2 began before the L0->L0 (maybe this detail is missing in my post).

We need to show two compactions because L0->L0 is only scheduled in cases where L0->L1 is impossible. The L1->L2 (which started first) makes L0->L1 impossible because it includes an L1 file that any L0->L1 would also need to include, and a file can only belong to one compaction. Thus we fall back to L0->L0 to quickly reduce L0 file count.

Q2: The output is a normal (but relatively larger) SST file in L0. You can see its number in the info log file. The compaction logs  something like "...Generated table #...".

**Comment by hshs1103** [comment]
Thank you for answering my question.

But the second question seems to have made you misunderstand. 

My second question means that I want to know the location of the C++ code for L0 compaction.(ex, compaction.cc ). 

It's hard to find because i'm not familiar with c++. 

And, I want ask more questions. 

In your answer, You said L0->L0 outputs a single large file. But I know that the size of the SST file is limited. Is it ok to create a single large SST file? Is there a problem with creating an SST file larger than another SST file?

please confirm again that I understand the process.

Initial state is same as below

![l1-l2-contend](https://user-images.githubusercontent.com/20452176/30042878-134b600a-922f-11e7-87c8-9c1e3f2e233b.png)

then L1->L2 compaction started. Because of L1->L2 compaction, L0->L1 compaction couldn't start. so RocksDB did L0->L0 compaction.

![l0compaction1](https://user-images.githubusercontent.com/20452176/30042915-5e89b724-922f-11e7-8fbe-6c76990a1ee5.png)

After L0->L0 compaction, Large SST file was generated.(Select all L0's SST files and merge them)

![compaction2](https://user-images.githubusercontent.com/20452176/30043456-6bb23752-9232-11e7-8367-068610ada3fc.png)

when L0->L0 compaction was finished, the state of the level is same as below

![compaction3](https://user-images.githubusercontent.com/20452176/30043941-8b8e715a-9235-11e7-806b-9caf675aa72d.png)

I understood the L0->L0 compaction as described above. Is this right?

If compaction occur later, there is only one large SST file in L0, so is this file selected so that it can be executed in parallel?

**Comment by ajkr** [comment]
Here is the file with the compaction picking algorithm: https://github.com/facebook/rocksdb/blob/master/db/compaction_picker.cc.

The general code for level compaction starts in `SetupInitialFiles`. It'll call `PickIntraL0Compaction` under the conditions I mentioned (L0->L1 is necessary but impossible due to a parallel compaction). `FindIntraL0Compaction` selects the files for compacting into a single big file in L0.

I'll answer your detailed questions later.

**Comment by hshs1103** [comment]
Thanks again for answering my questions. Your answer is great help to me. 

I'm looking at the compaction_picker.cc file now. 

I look forward to your answer to the rest of the detailed questions that I have made.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
