### ISSUE TITLE
[Question]db_bench test 

### ISSUE THREAD

**Issue by hshs1103** [facebook/rocksdb#2919]
Hi, dear all

I want to see how many times L0->L0 compaction occurs. 
So, i was experimenting with db_bench to check the frequency of L0->L0 compaction. 

The figure below shows the results from db_bench.

![image](https://user-images.githubusercontent.com/20452176/30728287-db24bc42-9f91-11e7-8ed6-6896819aa81b.png)
 

As far as I know, comp (cnt) means the number of compactions to Ln-> Ln + 1. 
That is, L0 (cnt) is known to mean L0->L1 compaction. Am I misinformed?
Is it possible to test L0 compaction in db_bench? If so, what should I do?

**Comment by ajkr** [comment]
@hshs1103 - the "L0" line represents files that were output to L0. Unfortunately it combines stats for files generated by flush and files generated by L0->L0 compaction.

One way to check if L0->L0 happened is by looking at the W-Amp column. If it's 1.0, that means data was written exactly once to L0 (when flushed), and never rewritten. If it's above 1.0, then at least some of the data was rewritten, which can only be caused by L0->L0.

For example, here's my output for a workload that's heavy in L0->L0 compactions:

```
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------
  L0     17/14  104.13 MB   0.8      1.2     0.0      1.2       1.9      0.6       0.0   2.9     57.1     87.4        22      1738    0.013     18M   7998
```

**Comment by ajkr** [comment]
If you need to know the exact number of times it occurred, I'd suggest checking the logs. I don't know of a reliable way to get it from our stats.

For example:

```
$ grep 'Compacted.*to L0' /dev/shm/dbbench/LOG | wc -l 
406
```

**Comment by hshs1103** [comment]
@ajkr  thanks. 
When i check the log as you said, the value comes out.
really really thank you!
please close this issue.
