### ISSUE TITLE
Hangs at RocksDB.loadLibrary();

### ISSUE THREAD

**Issue by NicholasBertazzon** [facebook/rocksdb#2965]
### Expected behavior
Load the library.

### Actual behavior
Hangs at "RocksDB.loadLibrary();" and exit with "Process finished with exit code -1073740791 (0xC0000409)". It was working flawlessly with RocksJava 5.7.3 . But not with 5.8.0.

### Steps to reproduce the behavior
The only thing I do is
`RocksDB.loadLibrary();`

OS: Windows 10 64bit
RocksDB version: 5.8.0 - Java (from maven)

**Comment by adamretter** [comment]
@NicholasBertazzon Yes, it seems I can reproduce this issue.

@yuslepukhin The Windows build seems to be broken in `lru_cache.cc` here:

```c++
LRUCache::LRUCache(size_t capacity, int num_shard_bits,
                   bool strict_capacity_limit, double high_pri_pool_ratio)
    : ShardedCache(capacity, num_shard_bits, strict_capacity_limit) {
  num_shards_ = 1 << num_shard_bits;
#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable: 4316) // We've validated the alignment with the new operators
#endif
  shards_ = new LRUCacheShard[num_shards_];
#if defined(_MSC_VER)
#pragma warning(pop)
#endif
  SetCapacity(capacity);
  SetStrictCapacityLimit(strict_capacity_limit);
  for (int i = 0; i < num_shards_; i++) {
    shards_[i].SetHighPriorityPoolRatio(high_pri_pool_ratio);
  }
}
```

The debugger seems to suggest the issue is with the line ` shards_ = new LRUCacheShard[num_shards_];`, but I am not sure why that would be as `num_shards_==16`.

@yuslepukhin Any chance you could shed some light on this?

**Comment by yiwu-arbug** [comment]
Just tagged 5.8.6 which include 0ec90a7 and 682db81.

**Comment by adamretter** [comment]
@yiwu-arbug Thanks for fixing
