### ISSUE TITLE
Minor FilePrefetch issue

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#3180]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

https://github.com/facebook/rocksdb/blob/master/util/file_reader_writer.cc#L609
### Expected behavior
We want to read the data at least as early as the specified read offset and thus the offset needs to be rounded down.
### Actual behavior
By rounding up the read offset when pref-etching data we forgo up to the alignment length of the data that we may be interested in.
### Steps to reproduce the behavior
Code inspection

**Comment by maysamyabandeh** [comment]
@siying can you chime in?
```
Status FilePrefetchBuffer::Prefetch(RandomAccessFileReader* reader,
                                    uint64_t offset, size_t n) {
  size_t alignment = reader->file()->GetRequiredBufferAlignment();
  uint64_t roundup_offset = Roundup(offset, alignment);
```

**Comment by siying** [comment]
@maysamyabandeh when this function was initially introduced, it was only used to prefetch the last 512KB of the data in the end of the file:

https://github.com/facebook/rocksdb/commit/666a005f9b9231800e31ea2276b8da89d665e608

Since the prefetch offset passed in is not accurately what we want to read from, rounding up doesn't hurt anything.

However, when the second use of the function comes, which is partitioned L0 index, it was not the case:

https://github.com/facebook/rocksdb/commit/1efc600ddfa4a8bf4cf042343d7a20199dfd76e5

so I think we should fix this from round-up to truncate-down to make the second use case more optimal.
