### ISSUE TITLE
buffer overrun in BackupEngineImpl::BackupMeta::StoreToFile

### ISSUE THREAD

**Issue by knutj42** [facebook/rocksdb#3228]
The "BackupEngineImpl::BackupMeta::StoreToFile" method in https://github.com/facebook/rocksdb/blob/master/utilities/backupable/backupable_db.cc loops over all the files in the database to produce a backup metadata file containing the crc-code of each file. The problem is that this information is first written to an in-memory buffer of a fixed size, without checking that there is room in the buffer.

The problematic piece of the code is this loop:

    for (const auto& file : files_) {
       // use crc32 for now, switch to something else if needed
       len += snprintf(buf.get() + len, buf_size - len, "%s crc32 %u\n",
                       file->filename.c_str(), file->checksum_value);
    }

If the number of files is large enough (in the range 200000-300000), this loop will cause a buffer overrun, since it constantly adds to the "buf" buffer. The size of the buffer is hardcoded to 10MB.

In our case this overrun usually causes a segfault, but it might theoretically cause other problems (including a corrupted database, if you are unlucky about what was in the memory-location the overrun overwrites).

Ideas on how to fix the problem:
 1. To dynamically grow the in-memory buffer when needed.
 2. To write directly to the target file with no in-memory buffer (or to a temporary file that can be renamed to the target filename when it has been completely written)

**Comment by ajkr** [comment]
The segfault I guess is caused by us assuming snprintf returns number of bytes actually written when truncation happens, but actually it returns number of bytes that would have been written.

```
If the output was truncated due to this limit then the return value is the number of characters (excluding the terminating null byte) which would have been written to the final string if enough space had been available
```

We should at least fix this so we can return you a non-ok status rather than segfaulting.

For really fixing it, we probably don't want to write directly to the target file as there can be millions of small writes, and we usually backup to a distributed file system. Dynamically growing in-memory buffer is good for me, or writing in batches each time we fill the 10MB buffer. Would you be interested in implementing a fix? :)

**Comment by RohanRathi** [comment]
Is this issue still valid? I'd like to work on it.

**Comment by ajkr** [comment]
We only fixed the segfault so a non-ok status is returned for this use case: https://github.com/facebook/rocksdb/pull/3255. Adding support for it is still needed. We'd be happy to review a contribution for it!
