### ISSUE TITLE
Support a faster way to check file overlap on SST ingestion

### ISSUE THREAD

**Issue by huachaohuang** [facebook/rocksdb#3540]
Hi, we have a use case that needs to ingest thousands of files to a DB one by one. We notice that the ingestion speed will drop constantly. The flame graph below shows that it is costly to check file overlap on each ingestion. My understanding is that if we can accept a sub-optimum ingestion result, we can just check the file endpoints to detect overlap, which is more lightweight.
So, can we add an option to use a faster way to check file overlap? Any other suggestion?

![flame graph](https://user-images.githubusercontent.com/7806468/36657137-6a5902f2-1b06-11e8-8cbb-86f8dd216062.png)

**Comment by siying** [comment]
In your case, is it likely that all or most files being ingested are overlapping?

**Comment by huachaohuang** [comment]
Yes, the test case above is designed deliberately to simulate the worst case. In that case, we ingest a batch of sorted files every time, but files in different batches overlap with each other.

**Comment by siying** [comment]
@huachaohuang in that case, I suggest we try following: for level 0, in the function: https://github.com/facebook/rocksdb/blob/3ae00472782571770e804aa177c9a813f9f82373/db/external_sst_file_ingestion_job.cc#L574-L604 rather than create a merging iterator for all L0 files and seek into it, we seek them one by one, and once we hit any overlapping we can exit, which will hopefully make your scenario significantly faster.

**Comment by huachaohuang** [comment]
@siying I have implemented an optimization thanks to your suggestion :)
