### ISSUE TITLE
Iterator::Valid() returns true when Iterator::status() is not Status::Ok

### ISSUE THREAD

**Issue by cdkamat** [facebook/rocksdb#3558]
### Expected behavior
If Iterator is valid, iterator->status() should also return Status::Ok. Is this a valid assumption? If `Iterator->status() != Status::Ok`, can the Iterator be used if `Iterator->Valid() = true` ?

### Actual behavior
We've observed that in certain cases if cache is full, Iterator::status() returns Status::Incomplete but Iterator::Valid() returns true.

```
ReadOptions iter_options;
iter_options.fill_cache = false;
iter_options.readahead_size = 256 * 1024;
rocksdb::Iterator *rocksdb_it = db->NewIterator(iter_options);

rocksdb_it->SeekToFirst();
assert(rocksdb_it->Valid());

// Iterator is valid, we expect status to return status.ok()
status = rocksdb_it->status();
cout << "Status of valid iterator: " << status.ToString() << endl;
assert(status.ok());
```

Output seen: 

```
Status of valid iterator: Result incomplete: Insert failed due to LRU cache being full.
iter_error: ../../../../rocksdb/tools/dump/iter_error.cc:182: int main(int, char **): Assertion `status.ok()' failed.
```

**Comment by siying** [comment]
@cdkamat we are aware of this behavior and modified wiki page for it: https://github.com/facebook/rocksdb/wiki/Iterator . We used to provide a wrong claim, and now we fixed it. We may will the behavior as what you described, but we don't have a concrete timeline for the change.

**Comment by cdkamat** [comment]
@siying : Thanks for the update. I see that the update to the Iterator wiki was made on Jan 23, I missed it. Can such things be added to the release notes? We, and I am sure other users, follow the release notes to know of issues that are found and fixed. In our application, we were assuming that the iterator would be Status::Ok if Iterator->Valid() returned true.

**Comment by siying** [comment]
@cdkamat sorry for the previously wrong description of the wiki. We will think of a way to make important correcting like this more visible.

**Comment by sihuazhou** [comment]
Hi @siying thanks for updating the description of the wiki. But, could I ask what is the best practice to use the `RocksIterator`? for example, If I have multi operation with the `Iterator` in one function, can I do the operations firstly and finally with one `iterator.status()`? Or I have to call the `iterator.status()` after every operation with the `iterator`?

Best, Sihua

**Comment by siying** [comment]
@sihuazhou it's up to your use case. The difference is scenario like this: assuming we have some keys in DB and some are corrupted:
```
a
b <-- corrupted
c <--  corrupted.
d
e
```
If you intend to scan all of them in order, you'll only see a, d and e. If you are fine with processing them all before checking the status, it is OK for you. But if you don't feel comfortable with seeing the gap of [b, c] implicitly skipped, you may want to check status for every key, so that you can discover the problem the first time you see something not following the correct state of the DB.

By the way, @al13n321 just committed a PR to fix this behavior, and it is expected to be released to the next release.

**Comment by sihuazhou** [comment]
@siying thanks a lot for your reply, just one more thing I'd like to confirm with you. As the example you given, if I loop all the records and finally with a `iterator.status()`, will the `failed status be cleared` that lead to I can't discover the problem? (I asked this because I found in [forward_iterator.cc](https://github.com/facebook/rocksdb/blob/8bf555f487d1de84a4fb19cb97b9ae1a8dbebc60/db/forward_iterator.cc) the `status_` could be reset to `OK`)

**Comment by al13n321** [comment]
After https://github.com/facebook/rocksdb/pull/3810 :
 (1) Valid() is always false if status() is not ok.
 (2) Next() and Prev() don't reset status().
 (3) Seek() and SeekForPrev() reset status().

Before that PR, (2) and (3) were usually true, but there were some cases when they weren't; e.g. switching direction using Prev used to clear status, and some types of error weren't reset by Seek.
