### ISSUE TITLE
IO error: while unlink() file No such file or directory

### ISSUE THREAD

**Issue by qingping209** [facebook/rocksdb#3573]
I observed the following in RocksDB LOG file:

2018/03/07-10:18:24.959597 7f5141f1d700 [DEBUG] [db/db_impl_files.cc:322] [JOB 100] Delete tmp/8509/rocksdb/000491.sst type=2 #491 -- OK
2018/03/07-10:18:24.959792 7f513a7fc700 [db/db_impl_files.cc:329] [JOB 0] Tried to delete a non-existing file tmp/8509/rocksdb/000491.sst type=2 #491 -- IO error: while unlink() file: tmp/8509/rocksdb/000491.sst: No such file or directory
2018/03/07-10:18:24.959817 7f513a7fc700 EVENT_LOG_v1 {"time_micros": 1520389104959809, "job": 0, "event": "table_file_deletion", "file_number": 491, "status": "IO error: while unlink() file: tmp/8509/rocksdb/000491.sst: No such file or directory"}

 JOB 0 is a  user thread and JOb 100 is a compaction thread.  With a little debugging and code reading, I find PurgeObsoleteFiles is called within CleanupIteratorState and BackgroundCallCompaction.   The way PurgeObsoleteFiles deletes obsolete files is: put files in database directory but not in live_sst_map，which is computed by FindObsoleteFiles.  So it's possible that calling PurgeObsoleteFiles in two thread will cause deleting the same file twice, which does not affect the correctness but cause a few confusion to users. 

Correct me if I'm wrong or I missed something.

**Comment by ajkr** [comment]
There's a couple more details that'll help explain why, in the usual case, a file gets deleted only once:

- A file is appended to `VersionSet::obsolete_files_` only once when its refcount reaches zero -- this could be due to a flush/compaction finishing or an iterator being released, among other things.
- A file in `VersionSet::obsolete_files_` is returned to exactly one caller of `DBImpl::FindObsoleteFiles` (see its call to `VersionSet::GetObsoleteFiles`). The corresponding `DBImpl::PurgeObsoleteFiles` is solely responsible for the deletion.

When `doing_the_full_scan` is true, however, `DBImpl::FindObsoleteFiles` can return arbitrary files, which invalidates the above reasoning. Do you know if it is true in at least one of your purges? I found one possible race condition for that case: if a file was deleted before the current Version but hasn't been purged yet, the next `FindObsoleteFiles` / `PurgeObsoleteFiles` with `doing_the_full_scan` will also pick it up for deletion. That's because it's still present in the directory but not present in `sst_live_map`.

**Comment by siying** [comment]
@qingping209 you don't have to set delete_obsolete_files_period_micros to 0 to have space taken by SST files reclaimed. It should almost always be reclaimed. full scan is a legacy. If can also have files cleaned if the normal mechanism misses any file because of bug, or corner case like no more writes coming, etc. Is there a reason you need to set this option?

**Comment by qingping209** [comment]
I thought setting delete_obsolete_files_period_micros = 0 would have the space reclaimed sooner, so I experimented with this option,  and forgot to remove it.

**Comment by ajkr** [comment]
Increasing that option should make the error message less frequent, but it can still happen as the full scan will eventually run in a compaction thread. Note the problem does not require running full scan in both threads, as `CleanupIteratorState` calls `FindObsoleteFiles` with `no_full_scan=true`.

**Comment by ajkr** [comment]
should be fixed by #3638, let us know if you still see the issue for SSTs.
