### ISSUE TITLE
Can BlobDB support CF now?

### ISSUE THREAD

**Issue by huachaohuang** [facebook/rocksdb#3834]
Hi, I'm exploring BlobDB recently and trying to adapt it to our system.
It turns out that BlobDB doesn't support CF now, and it was disabled in this commit https://github.com/facebook/rocksdb/commit/dcd36a6aee89e287d3db96710967e1f33389aec8.
After browsing the related code briefly, I think it was disabled because of the limitation of the previous implementation, and it seems no problem to support CF in the current implementation.
So, any plan to support CF in BlobDB, or any other concern?

**Comment by huachaohuang** [comment]
BTW, any plan to support GC in BlobDB?

**Comment by miasantreble** [comment]
@huachaohuang we primarily use GitHub issues for bug reports. Yi will answer your question in this thread shortly, but for future questions please post to Facebook group: https://www.facebook.com/groups/rocksdb.dev
Thanks

**Comment by yiwu-arbug** [comment]
@huachaohuang Thank you and PingCap for continue interest in BlobDB. 

Regarding CF support, there needs to be some work to support atomic writes to CFs via write batch. One simple approach is to make the keys in a write batch all write to a single blob file, which we are not doing right now. Also, as for now, BlobDB lack two main functionalities - GC and crash recovery, both of which needs to be implemented carefully to ensure compatibility with write batch. If write batch support is not needed, one can have multiple DBs instead of multiple CFs.

Regarding GC, we had some attempts but we are not getting it right yet. And I'm not able to give an ETA yet.

**Comment by yiwu-arbug** [comment]
@huachaohuang we can discuss in detail offline of the feature set you need for BlobDB so we can coordinate (on FB messenger or WeChat if you like).

**Comment by huachaohuang** [comment]
@yiwu-arbug Thanks for the explanation, we are still exploring the potential of BlobDB and haven't decided our next move yet. We are happy to discuss with you once we go further :)
