### ISSUE TITLE
Default value for `max_manifest_file_size`

### ISSUE THREAD

**Issue by bdarnell** [facebook/rocksdb#3851]
### Expected behavior

MANIFEST file should not be able to consume the entire disk

### Actual behavior

MANIFEST file grows without bounds. We've seen it grow as large as 24GB.

### Steps to reproduce the behavior

Use rocksdb in a long-running process with a lot of data churn. We also perform manual compactions in some cases. (I suspect that the 24GB case was caused by this manual compaction process running amok)

We've discovered the `max_manifest_file_size` option, which looks like it does what we want. Why does it default to unlimited? Is there some downside to enabling this option?

**Comment by miasantreble** [comment]
it's default to INT_MAX to avoid unexpected manifest roll-over due to organic growth.
You can set it to a smaller value that you are comfortable with. 
The smaller the limit is, the more frequently new manifest files will be created, that's the only downside I can think of.

**Comment by bdarnell** [comment]
Why would someone even be aware of an unexpected manifest roll-over? What possible undesirable effects could it have?

**Comment by riversand963** [comment]
The MANIFEST keeps partial or complete history of the state changes of the database. By setting `max_manifest_file_size` to `INT_MAX`, you are able to keep all the `VersionEdit`s. You can optionally set it to a smaller value to limit the amount of most recent history. We set the default to `INT_MAX` as a simplification because different users have different requirements. We rely on the user to configure this according to their hardware.
btw. Would you mind telling us how long it took RocksDB to accumulate 24GB in the MANIFEST file? Thanks!

Also cc @miasantreble, @ajkr and @siying

**Comment by bdarnell** [comment]
I don't know how long it took; this was a report from a customer deployment. Definitely less than two months, though.

I understand that keeping some history around may be useful, but surely setting some limit is better than letting this file grow to fill the entire disk (and even if you don't limit the size of the manifest file, the whole thing is discarded instantly when the process restarts. If history were that important you may want to save older manifest files too). Setting a limit of say 100MB would give you plenty of history without allowing this file to grow to surprising size.

**Comment by riversand963** [comment]
@bdarnell Thanks for the suggestion. We'll fix this shortly and keep you updated.
