### ISSUE TITLE
Add Java API for partial byte array lookup?

### ISSUE THREAD

**Issue by FelixGV** [facebook/rocksdb#3938]
Hi,

Could we add an API to the Java binding for getting a record with a subset of a byte array as the key?

So basically, instead of just having access to `get(byte[] key)`, could we also have access to `get(byte[] key, int offset, int length)`? This is available in the C++ API, and would be very useful for GC-sensitive applications.

FYI: we already tried posting this request on the Facebook Group but it does not seem to be getting tracked there (which is normal, of course, FB is not a ticketing system).

Cheers!

-F

**Comment by siying** [comment]
I like this idea. Are you interested in contributing the code?

**Comment by koldat** [comment]
Hi @siying 
I have written support for DirectByteBuffers that are much more flexible. There is even pull request for it. We are using that in our project for very long time (year) and it is much faster without Memory allocation hotspots. Byte arrays are quite inefficient in JNI, because JVM has to copy array twice.

https://github.com/facebook/rocksdb/pull/2283

I can rebase the pull request to current version if you like it.

**Comment by sagar0** [comment]
@koldat I'll take a look at your PR.

**Comment by koldat** [comment]
Thanks @sagar0 Let me know if you want to have rebased version to current master.

**Comment by koldat** [comment]
#2283 was just merged into master. If you are OK you can close the issue.

**Comment by adamretter** [comment]
@FelixGV I think your request is now satisfied via @koldat's work. Any problem, feel free to re-open the issue.
