### ISSUE TITLE
Write-Write Conflict Avoidance

### ISSUE THREAD

**Issue by adamretter** [facebook/rocksdb#410]
I am storing complex objects into Rocks which are de-composed into thousands of key value pairs. Each transaction in my system has it's own WriteBatch so that new objects are committed atomically. As well as replacing objects with new objects, it is also possible to update individual parts of an object and many updates may happen in a single transaction. A WriteBatch may contain of updates to many different objects, however it should be committed atomically or fail.

I am interested in detecting the issue of Write-Write conflicts in RocksDB. For example if I have two threads A and B and they each take a snapshot of the database. Let's say they both want to update the value of key1 dependent on knowing not just it's current value but also the current value of other keys in the database. The problem I have at the moment is that the first thread that does the write is fine, and succeeds, however the second thread will perform a write of a value determined by an old view of the database. Which leads to it updating the value of key1 to something invalid.

What I would like is a mechanism whereby when the second thread attempts to write it's WriteBatch, it realises the value of the key has changed since it took it's snapshot, and so no updates in the WriteBatch are committed. In many ways it is better explained in the first paragraph here - https://en.wikipedia.org/wiki/Snapshot_isolation#Definition

I may be mistaken, but I do not think Rocks offers anything to guard against Write-Write Conflicts?

I am not sure of the best way to achieve this, but one approach that I might suggest would be to create a new write function, called `WriteConditional` which takes a WriteBatch and a `Condition`. The Condition has to evaluate to `true` for the batch to be written atomically, if the condition returns false then no updates from the batch are written. Initially we would have a single Condition object perhaps called, `StableCondition` which takes a Snapshot. The purpose of StableCondition would be to make sure that the keys in the WriteBatch have not been changed in the database since the Snapshot was taken.
I am not sure how this would be achieved in Rocks, but perhaps it is as simple as checking the sequence number in the snapshot is greater-than-or-equal to the sequence number of each key in the WriteBatch?

I would also be interested to know how others are managing locking and transactions for updating complex objects in Rocks.

**Comment by igorcanadi** [comment]
Here's our approach for building some sort of transaction support in Mongo+RocksDB: https://github.com/mongodb/mongo/blob/master/src/mongo/db/storage/rocks/rocks_transaction.cpp

**Comment by fyrz** [comment]
@igorcanadi any chance to get something like this also in here ? Maybe as utility ?

**Comment by mdcallag** [comment]
We are trying get someone started on this within FB. I think it will be
useful and interesting to implement.

On Sat, Jan 24, 2015 at 3:30 PM, Jörg Maier <notifications@github.com>
wrote:

> @igorcanadi <https://github.com/igorcanadi> any chance to get something
> like this also in here ? Maybe as utility ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/rocksdb/issues/410#issuecomment-71342841>.
>



-- 
Mark Callaghan
mdcallag@gmail.com

**Comment by adamretter** [comment]
@igorcanadi I am going to need some time to study that code as I am not really a C++ guy. Any chance of you adding a high-level description of your approach to the class as a comment? I looked in the header file and can kinda grasp it, but I am not there yet.

**Comment by igorcanadi** [comment]
Each transaction gets a snapshot ID (they are monotonically increasing on every commit). For each key, we remember what was the last snapshot ID that it was committed. We also keep a set of keys that have uncommitted writes.

Every time a transaction wants to write to a key, we do:
1) check if the time that key was committed was earlier than transaction's snapshot ID. If that's not the case, that means the key was committed after our snapshot, so we can't write. abort the transaction.
2) check if key has outstanding writes (in the uncommitted set). If it does, some other transaction wants to write to it. abort the transaction
3) if all is good (means we can freely write to the key), we add the key to the uncommitted keys set.

On commit:
1) Every key that transaction has written, we update its snapshot ID, to reflect last time it was committed and to abort any transaction that might have read old version of the key.

This is specific to mongo because for mongo read_set == write_set. If you have arbitrary reads and writes, you might need to also record all the keys you have read.

**Comment by igorcanadi** [comment]
On commit, continued:
2) We remove the key from the uncommitted set.

**Comment by igorcanadi** [comment]
What I described above is very simple code. Most of the code in rocks_transaction.cpp deals with phasing out keys that have been written before the oldest transaction. Otherwise we'd need to keep all keys in memory forever. Here's the code without phasing out old keys: https://github.com/mongodb/mongo/blob/c902b92a9685d5be5490c701858378850ccb499f/src/mongo/db/storage/rocks/rocks_transaction.cpp

**Comment by siying** [comment]
We have a patch under review: https://reviews.facebook.net/D33435 Please feel free to take a look at it and tell you whether it helps with your use case!

**Comment by luengnat** [comment]
Any more updates to this issue? I saw some code got committed

**Comment by agiardullo** [comment]
Optimistic Transaction support is now in the RocksDB master branch.  Please take a look and let us know if this works for you.  

https://github.com/facebook/rocksdb/wiki/Optimistic-Transactions

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
