### ISSUE TITLE
MyRocks fails cmake check on thread_local

### ISSUE THREAD

**Issue by hermanlee** [facebook/rocksdb#4706]
https://github.com/facebook/mysql-5.6/issues/904

Since the original MyRocks cmake code was pulled in from the rocksdb cmake file and there are some MyRocks builds which hit problems here, I wonder if it is possible for building RocksDB to hit similar issues depending on compiler warnings. Opening up the issue to let the rocksdb team triage this. Sergey's proposed fix in MyRocks is to add code that utilizes tls to avoid the unused-variable warning, but Laurynas suggests we can probably remove the check altogether given universal support of thread local.

**Comment by riversand963** [comment]
@hermanlee thanks for bringing this issue up.
I agree it's better to fail the compilation than generate a library causing crashes. My concern here is how to make sure the very simple code snippet used for testing support for thread local can always succeed across multiple platforms and compilers. On a test machine, compiling the test code with flags `-W -Wextra -Wall -Wsign-compare -Wshadow -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-strict-aliasing -std=c++11 -fno-omit-frame-pointer -momit-leaf-frame-pointer -march=native` can succeed, thus setting HAVE_THREAD_LOCAL to true. The compiler is g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609 and the OS is Ubuntu 16.04.5 LTS.

According to https://github.com/facebook/rocksdb/blob/master/INSTALL.md, RocksDB does rely on C++11 that includes support for thread local (keyword `thread_local`). Our current codebase uses `__thread` more often. Therefore we should evaluate whether we can use `thread_local` instead of older `__thread`. Let me know if I have missed anything.

**Comment by riversand963** [comment]
@hermanlee we have updated the build_detect_platform script so that the error you see here should disappear.

In the future, I think we should stop the compilation if:
- user does not opt out iostats_context, and
- build_detect_platform thinks the platform does not support thread local due to error/warning when compiling the code snippet.

I am not sure whether we can always guarantee that the build_detect_platform does the right thing on all platforms. The case in https://github.com/facebook/mysql-5.6/issues/904 seems to suggest that we cannot. Therefore, I think the aforementioned approach should be a safenet to guard against potential hard-to-debug failures.

**Comment by riversand963** [comment]
@hermanlee #8117 addresses the problems mentioned in this issue. Closing.
Feel free to re-open if necessary.
