### ISSUE TITLE
C-api

### ISSUE THREAD

**Issue by hjiayz** [facebook/rocksdb#4999]
C-API 
https://github.com/facebook/rocksdb/blob/a62c6626e0ae27390013abcc94b42cecd6eb4497/db/c.cc#L3769

how to release rocksdb_snapshot_t?
free?

https://github.com/facebook/rocksdb/blob/a62c6626e0ae27390013abcc94b42cecd6eb4497/db/c.cc#L3818
miss columnfamily version

https://github.com/facebook/rocksdb/blob/a62c6626e0ae27390013abcc94b42cecd6eb4497/db/c.cc#L3925
miss columnfamily version

**Comment by siying** [comment]
Are you interested in contributing the code?

**Comment by hjiayz** [comment]
miss rocksdb_transactiondb_open_column_family

**Comment by hjiayz** [comment]
miss rocksdb_transactiondb_create_iterator_cf

**Comment by hjiayz** [comment]
miss rocksdb_transactiondb_merge_cf

**Comment by iSynaptic** [comment]
@siying If @hjiayz isn't interested in contributing the code, I am. I'm one of the maintainers on the Rust language bindings for RocksDB and I too have noticed a number of missing operations/overloads in the C API for the `TransactionDB` and `Transaction` classes.  

Beyond signing a CLA, what else is necessary to contribute?  Also, is there a release schedule for the native and Java libraries? I ask because I'd probably make the changes for the Java API as well, since it is dependent on the C API.

**Comment by hnakamur** [comment]
Hi, I just sent a pull request to add missing C APIs https://github.com/facebook/rocksdb/pull/5077

@hjiayz As for `rocksdb_transaction_get_snapshot`, the comment says `This snapshot should be freed using rocksdb_free` at https://github.com/facebook/rocksdb/blob/a62c6626e0ae27390013abcc94b42cecd6eb4497/include/rocksdb/c.h#L1489-L1491

@hjiayz @iSynaptic Thank you for creating the Rust language bindings for RocksDB! I'm looking forward for you to add transaction support!

**Comment by iSynaptic** [comment]
@hnakamur Thanks for doing this! Once it becomes available in a release, I'll work on adding support in the Rust binding.

**Comment by hjiayz** [comment]
rocksdb_transactiondb_drop_column_family
miss
