### ISSUE TITLE
Is it allow to call DB::Get during compaction?

### ISSUE THREAD

**Issue by xocodergit** [facebook/rocksdb#5057]
Hi guys, I use compaction filter to filter keys that are not need anymore. but in my design. the key and value cannot indicates whether this key is need to filter or not, i need to check **another value** so i can decide whether this key is need to filter.

so my question is : **can I call DB::Get in CompactionFilter::Filter?** 

**thanks a lot!**

**Comment by anand1976** [comment]
At the moment, we don't support it. I can't think what specifically can go wrong, but we have generally advised users against doing it.

**Comment by siying** [comment]
As what @anand1976 said, we strongly recommended users not do it. This can get tricky.
There are people doing it (like MyRocks) and it works OK. But you need to be really careful about it.
One major risk is that, if the database is blocking all writes because the compaction falls behind, and the compaction itself tries to insert, it is a deadlock condition.
Another thing to keep in mind is that compaction's effects are not immediately applied to DB. Rather, only when the whole compaction finishes, the source data is swapped. So you need to be careful about your consistency guarantee. It is more complicated if the DB crashes in the middle of compaction, or the compaction fails with failures like I/O errors.
Also, the thread local data structures, like perf context for example, gets a little bit trickier to reason about. In some extreme cases, we do see some failures because it. It may not be a killer, but you need to be careful about.

**Comment by xocodergit** [comment]
Got it, thanks to @anand1976 and @siying
