### ISSUE TITLE
why not rocksdb clear the merge-list when 'Get' called?

### ISSUE THREAD

**Issue by xocodergit** [facebook/rocksdb#5075]
Hi guys, i'm using 'merge' to findout the final status of data. 
But i've found-out that the merge-list is finally cleared in DB::Merge rather than DB::Get, I don't exacly understand what is this design for. 

Because in this design, **MergeOperator::Merge will be call in every DB::Get if the length of merge-list not reach 'max_successive_merges'**, which will cause a obviously waste of performance. Since it has been got a final value of merge-list when DB::Get, why not write this result and clear merge-list?  Why this operation is only doing when max_successive_merges reached?

Thanks a lot!

**Comment by anand1976** [comment]
This is more of a question about how RocksDB works than an issue. The public RocksDB Facebook group is a better forum for questions.

There is a tradeoff here between ```Get``` performance and memory usage. Since memtables are append only, doing a merge on ```Get``` being called will result in both the merged value, as well as the prior partial value, to be present in the memtable. The ```max_successive_merges``` config allows you to make the tradeoff between more aggressive merging, and potentially greater memory consumption, vs sacrificing some read performance.
