### ISSUE TITLE
assertion failure when attempting to ingest same file multiple times (using multiple hardlinks)

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#5133]
```
  // Background:
  // - Multiple hardlinks have the same result of `GetUniqueId()` if they point
  //   to the same file.
  // - When `move_files == true` and `write_global_seqno == false`,
  //   `GetUniqueId()` on the file is the same before and after the file is
  //   ingested to the DB.
  // - Block cache handles incorporate `GetUniqueId()` to avoid conflict across
  //   files.
  //
  // Problem:
  // If we ingest two hardlinks for the same file using `move_files == true` and
  // `write_global_seqno == false`, the second job got a validation failure
  // saying some keys had nonzero seqnum. That was because the validation logic
  // went through block cache, and due to the conflicting cache handles, we
  // could see the first file's data blocks when validating the second file.
```

Test case: https://github.com/ajkr/rocksdb/commit/54ec875880da8d926b0c3d9f95242b40282c66ea

Failure output:
```
./external_sst_file_test --gtest_filter=ExternalSSTFileTest.IngestMultipleHardLinksSingleFile
Note: Google Test filter = ExternalSSTFileTest.IngestMultipleHardLinksSingleFile
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ExternalSSTFileTest
[ RUN      ] ExternalSSTFileTest.IngestMultipleHardLinksSingleFile
db/external_sst_file_test.cc:1042: Failure
db_->IngestExternalFile({targets[1]}, ingest_opts)
Corruption: external file have non zero sequence number
[  FAILED  ] ExternalSSTFileTest.IngestMultipleHardLinksSingleFile (110 ms)
...
```

**Comment by ajkr** [comment]
Feel free to assign this to me. I just need help deciding on a solution. The easy way is to make file ingestion validation not go through block cache. But I wonder if there is anything else we should do to prevent users from getting into a state where their DB has multiple files with the same value for `GetUniqueId()`.

**Comment by riversand963** [comment]
@ajkr, thanks for reporting. Would it be easier if just require the user not to ingest the same file twice, or detect whether there are multiple hard links to the same file? I am asking because I am trying to understand the use case.

**Comment by ajkr** [comment]
Maybe. The use case is an application finishes ingesting a file before it crashes, but crashes before it marks its ingestion is successful. Then after it restarts it will retry ingesting the same file, not knowing that at the RocksDB level it finished before the crash. For that case it is nice if the ingestion operation is idempotent.

**Comment by riversand963** [comment]
I see. So in your example, the block cache outlives the crashed application?

**Comment by ajkr** [comment]
Good question. Our block cache does not survive the crash recovery. But if there are reads after the crash recovery but before the second ingestion attempt, the block cache may be repopulated enough to cause the problem. My understanding of the scenario is not good enough to say 100% this is the case, though.

**Comment by ajkr** [comment]
Too bad the manifest doesn't have unique ID. That might be an easy way to fail file ingestion here. I wonder what you and @siying think about that approach.

**Comment by bdarnell** [comment]
> The easy way is to make file ingestion validation not go through block cache.

I don't think that would work here. If we bypassed the cache, the second ingest would succeed, but then we'd have imported two copies of the same file (by inode) that would be assigned two different sequence numbers. Only one of those sequence numbers can appear in the block cache.

I think we need the second ingest to fail, but with an error that cleanly indicates that this file has already been ingested. 

Our best candidate for a workaround at the moment is to persist a flag indicating "this file may have been ingested", and if flag is set when we try to ingest a second time, make a copy instead of a hard link.

**Comment by petermattis** [comment]
I've asked @ajkr this question elsewhere: is there a reason RocksDB uses the inode number for the cache handle for sstable blocks instead of the file number? The file number seems like a more obvious choice. RocksDB knows the file number for any sstable it reads or writes in the normal code paths (though there appears to be some plumbing to get this down into `BlockBasedTable`. And for ingested sstables the file number is assigned before any of the external sstables are accessed.

Using the file number for the cache handle would eliminate the problem here, as the second ingestion would give the sstable a different file number and thus not run into existing blocks in the block cache. I'm guessing there are downsides to using the file number that I'm not seeing.

**Comment by ajkr** [comment]
I'd guess it uses unique id because the block cache may be shared across
multiple rocksdb instances, each of which numbers its files independently.

**Comment by petermattis** [comment]
> I'd guess it uses unique id because the block cache may be shared across
multiple rocksdb instances, each of which numbers its files independently.

That's a good point, though a per-instance unique ID could have solved that. I believe this unique ID wouldn't have to be persisted, so it could be stored in process (or it could be something like the pointer value of the `rocksdb::DBImpl`. I suppose at some point though it feels like you're just getting to something like the current inode number / device number cache handle that RocksDB uses.

**Comment by siying** [comment]
@ajkr we do plan to add a unique DB ID to manifest. We can't prioritize in the near future though.

Btw, <db, file_name> is not guaranteed to identify the same file all the time. We may put block to block cache while we write 0003.sst, while before the compaction finishes, the file is closed, so that file is abandoned. After reopening the DB, 0003.sst will be garbage collected, and a new 0003.sst may be created.

A more tricky case is that the DB is copied around, or recovered from backup, so that the DB is in theory the same one, but the files are regenerated.

**Comment by ajkr** [comment]
> we do plan to add a unique DB ID to manifest. We can't prioritize in the near future though.

I'll try it this week and see how hard it is.
> A more tricky case is that the DB is copied around, or recovered from backup, so that the DB is in theory the same one, but the files are regenerated.

**Comment by siying** [comment]
@ajkr I referred to the problem of copying SST files around for the problem that <db_id, sst_number> cannot be permanently identify which file it is in the life time.

Back to the original issue, with option `IngestExternalFileOptions.write_global_seqno = false;` by @riversand963  , we won't update SST file to be loaded. So I can't think of a problem of loading the same file to multiple DBs. Did you try that?

**Comment by ajkr** [comment]
> @ajkr I referred to the problem of copying SST files around for the problem that <db_id, sst_number> cannot be permanently identify which file it is in the life time.

Oh sorry this problem reminded me of the problems with running RocksDB on an object store. Never mind.

> Back to the original issue, with option IngestExternalFileOptions.write_global_seqno = false; by @riversand963 , we won't update SST file to be loaded. So I can't think of a problem of loading the same file to multiple DBs. Did you try that?

We do use that. We only intend to load the file into one DB. The problem happens with move-based ingestion (i.e., `write_global_seqno == false`) if the DB crashes after the file got committed to the DB but before the source file got deleted. So after recovery, the source file is still around, and we call move-based ingestion on it a second time. However, then it fails with this hard-to-debug corruption error since the second ingestion's validation sees data blocks that are part of the first file due to conflicting block cache handles.

**Comment by ajkr** [comment]
There is a workaround now though to make a copy of a file before using move-based ingestion if it has multiple hardlinks. The assumption is that any hardlink besides the one created by `SstFileWriter` would be in the RocksDB directory, indicating a previous move-based ingestion might've succeeded. I do wonder if other users of move-based ingestion can run into these problems, though.

**Comment by huachaohuang** [comment]
@ajkr Thanks for reporting, I encounter the same problem. I also try to solve it by counting hard links, but I'm thinking of a corner case:
1. We ingest a file to RocksDB successfully
2. RocksDB restarts and recovers
3. RocksDB loads some data blocks from the ingested file into the cache
4. RocksDB compacts the ingested file and deletes it, but some data blocks of the ingested file are still in the cache
5. We check that the file has only one hard link and try to ingest the file again

**Comment by huachaohuang** [comment]
@ajkr I check the cockroachdb commit, it falls back to a copy ingestion if the hard link ingestion fails. Seems I have to do the same thing.

**Comment by ajkr** [comment]
#6429 should have fixed this by moving global seqno out of the cached block.
