### ISSUE TITLE
can rocksdb's block improve performance?

### ISSUE THREAD

**Issue by eejoin** [facebook/rocksdb#519]
We're doing a block cache size influence on the performance,and we found that increase the size of block cache almost has no effect on performance, even in large quantity of the data set.

because of the influence of os page cache? What circumstances increase block cache size can obtain better performance?

In addition, I found that  Rocksdb's [Performance Benchmarks](https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks) said that the block cache size is 1G,But the block cache size is set to 1048576 of actual test, and I read the code found that the unit of size maybe byte, is that right?
_**cs=1048576;** of=500000; si=1000000; ./db_bench --benchmarks=readrandom --disable_seek_compaction=1 --mmap_read=0 --statistics=1 --histogram=1 --num=$r --threads=$t --value_size=$vs --block_size=$bs **--cache_size=$cs**_

**Comment by igorcanadi** [comment]
Are you compressing data? One difference between os cache and block cache is that block cache is uncompressed. OS cache keeps compressed data.

Also, if your read pattern is very random, you won't get any benefits from block cache, because of low hit rate. Did you check what is your block cache hit rate?

**Comment by paultuckfield** [comment]
One useful course of analysis is to make sure no IO's take place at all (the perfect cache), then contrast to all IOs (no cache).   Where does the observed perf of your cached workload fall relative to these?

**Comment by baotiao** [comment]
@igorcanadi  Yes, we compressing the data. But we found that the size of the block cache size dosen't affect the Performance. We analysis the result that maybe because the os has page cache, we we read a block from sst file, os help us cache the block. So, as you say, the only different between os's page cache and the block cache is that block cache is uncompressed. But is some situation, If you define too large block cache size, lager than the physical memory, the performance will be slower than with no cache size, because the too lager block cache situation my use os's swap which is store in file system..

**Comment by baotiao** [comment]
So in my opinion, may be the block cache is not necessary..

**Comment by pengxindong** [comment]
@igorcanadi I used db_bench to test random read performance,the data is compressed, after compressed the data is about  5G,and the useful memory is about 3G.

as you said,the difference between os cache and block cache is that block cache is uncompressed, if  CPU is not the bottleneck, the effect of block cache is not obvious?

**Comment by ekg** [comment]
So how does one turn the block cache completely off?

**Comment by igorcanadi** [comment]
no_block_cache = true

**Comment by siying** [comment]
db_bench's readrandom benchmark queries all keys with equal chance without any locality. So if you have 100GB with 1GB block cache, block cache at most optimize 1% of reads, which generates almost no change.

However, now we have a new function to -read_random_exp_range, if you set "read_random_exp_range=15" or so will make hotness of keys different. In that case, you'll see a difference of block cache sizes. You can give it a try.

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by sagar0** [comment]
I hope your issue is resolved.
Closing this issue as it is more than an year old. Please feel free to reopen if you think this issue is still relevant and/or has been closed in error.
