### ISSUE TITLE
Block cache is not transparent

### ISSUE THREAD

**Issue by jsteemann** [facebook/rocksdb#5322]
When enabling the block cache for storing uncompressed data blocks and at the same time enforcing the block cache's `strict_capacity_limit`, reads that try to populate the block cache but fail due to the capacity restriction fail with Status::Incomplete.

I had hoped that the block cache would behave transparently, i.e. serve an item from the cache if it's present in it, and fall back to reading it from disk if the block cache is turned off or can't be used for any other reason.

That the block cache sometimes returns Incomplete is unexpected to me, and on the application level there is not much that can be done about it if it happens. The block cache instance is created only once at the beginning with the capacity limit flag set and then simply used afterwards. When the Incomplete errors happen, reading will simply fail and the only way to prevent this from happening is trying again with different options etc. 
But this seems less than ideal.

Is it possible to adjust the behavior that if insertion into the block cache fails, the read simply falls back to what it would do if the block cache were disabled?
I gave this a quick try in the `block_based_table_reader.cc` and at least there it seemed to work. However, I don't know any of the internals and where else it is used, so I won't open a PR with the changes.
A valid counter argument against changing the behavior is that when bypassing the cache due to the capacity limit being reached the performance may degrade. I think this is true, but it may be preferable to "random" errors. So I am wondering whether the behavior could be chosen by embedder.

### Expected behavior

Reading values from the database succeeds regardless of the block cache configuration.

### Actual behavior

Reading values from the database succeeds if uncompressed values fit into the block cache, but fail with Status::Incomplete if uncompressed values don't fit into the block cache and the `strict_capacity_limit` is used.
It works when `strict_capacity_limit` is not used.  

### Steps to reproduce the behavior

To reproduce, create a very small block cache with `strict_capacity_limit` and then insert values that will be too big to be held by the block cache's shards.

**Comment by jsteemann** [comment]
Update: the situation hasn't changed up to now.
It would be useful if the block cache could be made completely transparent, so that results of Status::Incomplete can be avoided when an entry does not fit into the block cache.
Otherwise the whole burden of sizing the block cache correctly in resource-constraint environments (where `strict_capacity_limit` is required to prevent OOM) is completely put on the user.
Thanks!

**Comment by jsteemann** [comment]
Potential fix: https://github.com/facebook/rocksdb/pull/9975

**Comment by pdillinger** [comment]
Unless you really want to allow Incomplete for some queries AND not for others, I don't think the option makes sense.

If you set strict_capacity_limit=true and return_incomplete_on_too_large_cache_inserts=false, then only when block cache has nothing to evict ("full"), Get and Iterators, etc will temporarily load blocks into memory beyond block cache memory capacity in order to answer the query and free them ASAP (subject to life of Iterator or PinnableSlice, etc.).

If you set strict_capacity_limit=false, then only when block cache has nothing to evict ("full"), Get and Iterators, etc will temporarily load blocks into memory beyond block cache memory capacity in order to answer the query and free them ASAP (subject to life of Iterator or PinnableSlice, etc.). The difference is that with `strict_capacity_limit=false`, the blocks logically go into the block cache beyond its capacity (logically = typically the same memory allocator is used in either case), so that (a) other queries accessing the same block can share the memory for those blocks rather than incurring redundant I/O and memory usage, and (b) if block cache is no longer full when the block is eligible to be freed (no longer referenced), it doesn't have to be freed ASAP.  This has big advantages compared to your proposal, with the only downside being that you can't select which queries you're willing to exceed block cache capacity with.

With enhancements to the Cache API, we could make enforcement of "strict capacity limit" an option at query time, though it's awkward because we need to predict at Lookup time whether there will be capacity to insert within capacity at Insert time; otherwise, we end up loading the block into memory only to discover we violated our space constraints. TBD whether solving this problem would require so much extra logic that it impacts critical block cache performance.

**Comment by jsteemann** [comment]
@pdillinger : ok, thanks for sharing your thoughts. I think it is fine for me to move forward without the extra option I suggested in the PR. Simply have to be extra careful with the `strict_capacity_limit` then and will adjust client application code. Closing this issue and PR #9975 now.

**Comment by sourabhedake-mm** [comment]
@pdillinger 
I have enabled `--rocksdb.enforce-block-cache-size-limit`

However, after enabling this, I got the issue mentioned in the ticket.
Inserts should be successful even if the block cache is full.

Why do we have a dependency on cache implementation for operations like insert?
