### ISSUE TITLE
is there any way faster to ingest sst file

### ISSUE THREAD

**Issue by haiping-kernel** [facebook/rocksdb#5770]
I have hundreds of sst files,  total size 400G. when I ingest them to empty databases(64 rocksdb instance)  in disk parallel, it use time 2 hours,  is there any way faster?????

**Comment by anand1976** [comment]
Can you provide a snippet of the code you're using to ingest? And what is the bottleneck you're observing - is it the copy to disk?

**Comment by siying** [comment]
@haiping-kernel if the input data is pre-sorted, so that those SST files are already key range partitioned, it will be really fast to ingest. Otherwise, some compaction might be needed. If you are OK with temporarily doubling the space when ingesting the data, you can first disable automatic compaction, ingest them all, and do a manual full compaction in the end.
