### ISSUE TITLE
Java: Add methods to pass byte array to key/value in iterator

### ISSUE THREAD

**Issue by jurmous** [facebook/rocksdb#6282]
Currently the RocksIterator has two methods `key()` and `value()` to retrieve a byte array with the current key/value. These values are likely directly read into other representations like String/Int etc. These methods create a new byte array on each invocation which adds to memory and thus garbage collection. It would be more efficient to add variants in which the byte array is passed with possible offset and length to read into and a count of the length of the key/value as return. A similar method already exists inside RocksDB.java for get as:

```
/**
   * Get the value associated with the specified key within column family*
   *
   * @param key the key to retrieve the value.
   * @param offset the offset of the "key" array to be used, must be
   *     non-negative and no larger than "key".length
   * @param len the length of the "key" array to be used, must be non-negative
   *     and no larger than ("key".length -  offset)
   * @param value the out-value to receive the retrieved value.
   * @param vOffset the offset of the "value" array to be used, must be
   *     non-negative and no longer than "value".length
   * @param vLen the length of the "value" array to be used, must be
   *     non-negative and and no larger than ("value".length -  offset)
   *
   * @return The size of the actual value that matches the specified
   *     {@code key} in byte.  If the return value is greater than the
   *     length of {@code value}, then it indicates that the size of the
   *     input buffer {@code value} is insufficient and partial result will
   *     be returned.  RocksDB.NOT_FOUND will be returned if the value not
   *     found.
   *
   * @throws RocksDBException thrown if error happens in underlying
   *    native library.
   */
  public int get(final byte[] key, final int offset, final int len,
      final byte[] value, final int vOffset, final int vLen)
      throws RocksDBException
```

We use a lot of iterators to read data. This method would enable us to recycle a byte array during reading so it saves a lot of byte array creation and thus garbage collection pressure.

**Comment by adamretter** [comment]
@jurmous there is actually a move to unifying around `ByteBuffer` which then affords us a single class whose memory can be Java on-heap or in native on-heap (outside of GC).

I recently sent a PR to migrate the Comparator interface in this way, which is under consideration at the moment - https://github.com/facebook/rocksdb/pull/6252

I agree that the interface of `RocksIterator` could be improved for reuse of arrays. I think we have a few options though, and I would ideally like to standardise on `ByteBuffer` rather than `byte[]` as the interface. There is also a push towards that here - https://github.com/facebook/rocksdb/pull/2283, which I hope we can merge with some small changes after #6252.

Let's see how it goes...

**Comment by jurmous** [comment]
@adamretter Sounds great to hear there is a momentum to unify around ByteBuffers. I think that indeed more can be improved by those. I will follow the progress in #6252 for now!
