### ISSUE TITLE
Get size of value without reading the value

### ISSUE THREAD

**Issue by theolivenbaum** [facebook/rocksdb#6394]
Is there any way of reading what's the size of a value in a RocksDB database without having to actually read  the value (and thus not incurring the cost of allocations)?

**Comment by anand1976** [comment]
There is no API to just read the size of the value. You may be able to do it indirectly by calling Get() and MultiGet() variants that return the value in a PinnableSlice (or GetMergeOperands() if you write Merges and don't want them to be merged in order to calculate the final value). In most cases, the PinnableSlice will reference the value in the block cache and avoid memory allocation. You can get the size from the PinnableSlice.
