### ISSUE TITLE
[BUG] ImportColumnFamily::Prepare fail

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#6647]
https://github.com/facebook/rocksdb/blob/fdf882ded218344c136c97daf76dfb59e4bc155f/db/import_column_family_job.cc#L67

sstableKeyCompare does not compare LSN, so it is legal that two neighbouring ssts in the same level have have sstableKeyCompare(i.max, (i+1).min) == 0

**Comment by anand1976** [comment]
Cc @siying @riversand963 @ajkr as they have more expertise in file ingestion.

**Comment by wolfkdy** [comment]
I strongly suggest not remove the lsn information on the bottommost level when doing compaction.
The benifit of several bytes space reduce is too small to match the lsn information lost, which may block the way when sometime in the future, new features may rely on this.

**Comment by ajkr** [comment]
> I strongly suggest not remove the lsn information on the bottommost level when doing compaction.
> The benifit of several bytes space reduce is too small to match the lsn information lost, which may block the way when sometime in the future, new features may rely on this.

It's possible, but keep in mind there have also been new optimizations that rely on the seqnum zeroing in bottommost level like #5244. So the benefit is more than just a few bytes space (per key).

> Cc @siying @riversand963 @ajkr as they have more expertise in file ingestion.

I'll fix it, it should just use internal comparator rather than `sstableKeyCompare()`. The latter was intended for checking whether a compaction input file's neighboring files need to be included in the same compaction. It's not intended for checking internal key invariants.
