### ISSUE TITLE
why LOG.old.* keep growing even after set keep_log_file_num

### ISSUE THREAD

**Issue by walterzhaoJR** [facebook/rocksdb#7130]
here is my conf
![image](https://user-images.githubusercontent.com/22393698/87494460-a46e6300-c681-11ea-952f-42630489926e.png)
but the log file:
![image](https://user-images.githubusercontent.com/22393698/87494476-b5b76f80-c681-11ea-84dc-5390cd171ea0.png)
![image](https://user-images.githubusercontent.com/22393698/87494488-bd771400-c681-11ea-8fb5-0cd4d05a9382.png)

**Comment by akankshamahajan15** [comment]
Can you share the value of  Options.keep_log_file_num in LOG file and OPTIONS-000067.

**Comment by walterzhaoJR** [comment]
Unfortunately, my environment has been cleaned up.
RocksDB Version is 5.18.3

**Comment by akankshamahajan15** [comment]
Till 6.2 release, auto roll logger, options.keep_log_file_num enforcement is triggered by events like DB reopen or full obsolete scan happens.  In the mean time, the size and number of log files can grow without a limit. Patch has been added in the next release to put a stronger enforcement to the option, so that the number of log files can always under control.  So that might be the reason in your case.

**Comment by walterzhaoJR** [comment]
OK.Thank you

**Comment by walterzhaoJR** [comment]
Excuse me.I want to ask which commit corresponds to the modification of the  question.
@akankshamahajan15 
Thank you very much!

**Comment by akankshamahajan15** [comment]
> Excuse me.I want to ask which commit corresponds to the modification of the question.

https://github.com/facebook/rocksdb/pull/5370

**Comment by zhichao-cao** [comment]
The issue should be resolved in new RocksDB release. Close it.
