### ISSUE TITLE
Add `ParseInternalKey()` runtime check in optimized builds that keys are eight bytes or longer

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#7429]
This would be a sanity check that is expected to never fail except on faulty hardware, which we'd like to detect earlier.

**Comment by ramvadiv** [comment]
ParseInternalKey() already seem to have check for internal key to be >= 8 bytes (even in optimized builds). https://github.com/facebook/rocksdb/blob/master/db/dbformat.h#L328 

@ajkr pointed of some crashes that indicate some corruption after this check   -  we are not able to clearly explain the root cause of those crashes yet (other than application causing a corruption to Internal Key memory area after the call to ParseInternalKey()). Will fix PR#7430 first and then revisit this PR...

**Comment by ajkr** [comment]
> @ajkr pointed of some crashes that indicate some corruption after this check - we are not able to clearly explain the root cause of those crashes yet (other than application causing a corruption to Internal Key memory area after the call to ParseInternalKey()). 

Agreed `ParseInternalKey()` is not the place checks are needed. After creating this issue, I noticed some (most?) SIGSEGV crashes are before `ParseInternalKey()`, in particular when comparing a corrupt (zero length) key to a valid key. There may be an opportunity to do more validation in that area.

**Comment by ajkr** [comment]
I believe this was done.
