### ISSUE TITLE
CompactRange with change_level = true will move all the files of the level

### ISSUE THREAD

**Issue by Connor1996** [facebook/rocksdb#7441]
As comment of change_level said, compacted files will be moved to the minimum level capable of holding the data or given level.
https://github.com/facebook/rocksdb/blob/8f8264032dbf8667b0792f683b1221a74cf8e4bf/include/rocksdb/options.h#L1531-L1533
Whereas in `RefitLevel`, it moves all the files of the level to target but not compacted files https://github.com/facebook/rocksdb/blob/8f8264032dbf8667b0792f683b1221a74cf8e4bf/db/db_impl/db_impl_compaction_flush.cc#L1377-L1385

I'm not sure whether it is in purpose?

**Comment by ajkr** [comment]
The goal of change_level is to support compaction migrations (e.g., changing num_levels, changing level_compaction_dynamic_level_bytes, etc.). Such migrations are only possible if we migrate all the files in the level. I agree it is pretty confusing because we allow `CompactRange()` to specify non-nullptr endpoints together with `change_level = true`, which almost guarantees the level change (`RefitLevel()`) step will fail.

Is there a use case for moving only some of a level's files to another level?

**Comment by Connor1996** [comment]
> The goal of change_level is to support compaction migrations (e.g., changing num_levels, changing level_compaction_dynamic_level_bytes, etc.). Such migrations are only possible if we migrate all the files in the level. I agree it is pretty confusing because we allow `CompactRange()` to specify non-nullptr endpoints together with `change_level = true`, which almost guarantees the level change (`RefitLevel()`) step will fail.

Thanks for explanation. No use case, just want to leverage it for unit test to reproduce some cases.

**Comment by ajkr** [comment]
Tested it just now - it returned a reasonably good error without doing any damage (maybe the partial compaction work is wasted, idk).

```
NotSupported: Not implemented: Levels between source and target are not empty for a move.
```

 I think it is fine to support this if someone wants, but we don't have a use case either.
