### ISSUE TITLE
Getting an existing value from rocksdb using the Java API is slow

### ISSUE THREAD

**Issue by jaceding** [facebook/rocksdb#7544]
Using Java API to get an existing value from rocksdb is far slower than that from Java from map. Rocksdb also has memtable. Why is the speed so different?
```
        RocksDB db = RocksDB.open(options, logDir);
        String key = "test";
        String value = "lcd901yb0tdokl5ioepglkhexx806ihf5ueyhg1bb4fsnho8p2s";
        db.put(key.getBytes(), value.getBytes());
        db.get(key.getBytes());
        Map<String, String> map = new HashMap<>();
        map.put(key, value);

        int num = 100000;

        long sT = System.currentTimeMillis();
        for (int i = 0; i < num; i++) {
            map.get(key);
        }
        long eT = System.currentTimeMillis();
        System.out.println((eT - sT)  + "ms");
        long sT2 = System.currentTimeMillis();
        for (int i = 0; i < num; i++) {
            db.get(key.getBytes());
        }
        long eT2 = System.currentTimeMillis();
        System.out.println((eT2 - sT2)  + "ms");
```
output：
2ms
65ms
Why is the speed so different?

**Comment by jaceding** [comment]
Because JNI?

**Comment by adamretter** [comment]
@jaceding JNI does impose some overhead. You would have to compare the Java API against the C++ API to get a better comparison. Comparing against a Java HashMap does not really make sense.

We are doing some work on improving the API performance at the moment. You can see the progress here - https://github.com/evolvedbinary/jni-benchmarks/pull/3

Also have you tried using the ByteBuffer methods instead of byte[]?
