### ISSUE TITLE
What is the difference between FullMergeV2(existing == nullptr) and PartialMergeMulti

### ISSUE THREAD

**Issue by xphoenix** [facebook/rocksdb#7583]
As per my understand ```FullMergeV2``` with ```_existing_value==nullptr``` effectively means that rockdb found sequence of merge operation witthout base PUT value. That looks exactly the same situation as ```PartialMergeMulti``` should solves. 

So the question is - why both needs? Am I miss something?

**Comment by pdillinger** [comment]
Situation 1: Put(k, w), Merge (k, x), Merge (k, y), Merge (k, z)
Situation 2: (nothing previous on k), Merge (k, x), Merge (k, y), Merge (k, z)

FullMergeV2 for k in Situation 1 will never be passed existing_value=nullptr. In Situation 2, existing_value=nullptr unless we've done a previous FullMergeV2 on k to get a value.

PartialMergeMulti for k could be called with x,y or y,z in either situation, but never with w because that would use FullMergeV2 instead.
