### ISSUE TITLE
Is there a problem of ExportColumnFamily, how do I import column family without metadata?

### ISSUE THREAD

**Issue by sunxiao2010n** [facebook/rocksdb#7705]
I used ExportColumnFamily() to export data.

  _virtual Status ExportColumnFamily(ColumnFamilyHandle* handle,
                                    const std::string& export_dir,
                                    ExportImportFilesMetaData** metadata);_

 sst files were exported to the export_dir. but the returned metadata contains no files

 _struct ExportImportFilesMetaData {
   std::string db_comparator_name;       // Used to safety check at import.
   std::vector<LiveFileMetaData> files;  // Vector of file metadata.
 };_

and is there a way to import sst files without metadata to describe them?

**Comment by ltamasi** [comment]
@sunxiao2010n  Looking at the `ExportColumnFamily` code, `metadata` only gets populated if the export succeeds. Since in your case it was empty, I'm assuming the job had failed and returned a non-OK `Status`. So whatever is in the export directory is most likely unusable, and you probably wouldn't want to import it anyways.

Now, failed column family exports are supposed to clean up after themselves (i.e. delete all files created). It is possible that this cleanup failed due to e.g. a filesystem issue, and that's why some files were left behind. You might find details about why the export and/or the cleanup failed in the RocksDB info log (`LOG*` files).

**Comment by ltamasi** [comment]
Closing this since it does not seem to be a RocksDB bug.
