### ISSUE TITLE
Why don't support some method using right reference

### ISSUE THREAD

**Issue by darionyaphet** [facebook/rocksdb#7708]
### Expected behavior

Why don't support some method using right reference  for example:

```
virtual Status Put(const WriteOptions& options,
                   ColumnFamilyHandle* column_family,
                   Slice&& key,
                   Slice&& value) = 0;
```

**Comment by pdillinger** [comment]
Slice is a no-op for destruction, so there's no reason for move semantics on Slice.

If you are thinking about std::string&&, even that is not helpful because RocksDB doesn't keep K&V strings around as individual buffers after the call to Put. The data is packed into other structures. So move semantics would accomplish nothing except have RocksDB free your data ever so slightly before you would free your data. And it would make the API more complex and susceptible to logic error.
