### ISSUE TITLE
Settings for a database with a big number of column families

### ISSUE THREAD

**Issue by aleksuss** [facebook/rocksdb#8009]
Hello. I noticed a performance regression when I had increased a number of column families in my app from 4 to 39. Do I need to use special settings for such case ? At the current moment I've found out that a reason of such behaviour is a continuously growing size of a WAL journal. If I manually limit `max_total_wal_size` to e.g. 1 mb than everything works good. But I think it's a bad idea to have such small WAL journal. Could you please suggest what I have to change in my rocksdb settings to avoid the regression. 
Some details:
1. I use default settings.
2. After restarting an application (without dropping a database) the regression is disappeared for some time. (I.e. an amount of a data doesn't affect performance).

Thanks for advice.

**Comment by anand1976** [comment]
Can you provide some more details on the nature of the performance regression? Was it read throughput, or write throughput, CPU utilization or something else? Its very strange that limiting ```max_total_wal_size``` to 1MB improved performance, since such a small size means very frequent flushes.

**Comment by aleksuss** [comment]
I guess a regression occurs in a read throughput. But even in empty column families or with tiny number of elements. Here is an example of heaviest stack trace:
<img width="1044" alt="Screenshot 2021-03-02 at 10 17 15" src="https://user-images.githubusercontent.com/3829201/109618691-838b4d00-7b40-11eb-88f8-ad7efeff829b.png">
CPU utilization is gradually growing till 100%.

**Comment by anand1976** [comment]
At first glance, looks like its due to a lot of range deletions. IIUC, range deletions are converted to a fragmented tombstone list in order to process a Get/Iterator. The fragmented tombstone list is constructed once for an SST file and stored in the file, but constructed each time for a memtable, hence the higher overhead. This would explain why a smaller ```max_total_wal_size``` improves performance.

I'm not sure if there's a good solution for this though. Cc @ajkr
