### ISSUE TITLE
Corruption upon power loss after restoring a backup

### ISSUE THREAD

**Issue by Spferical** [facebook/rocksdb#8500]
If power loss occurs shortly after restoring a backup, database files may be left in an incomplete state. A workaround is to manually sync the filesystem after the restore.

Side note, corruption also happens if power cuts off during a restore, but this seems to be a deliberate choice of the current implementation (`BackupEngineImpl::RestoreDBFromBackup` effectively starts off with an `rm -r`). Is there any interest in making restores atomic/would that be feasible?

### Expected behavior

Power loss can cause loss of data (last N commits), but will not corrupt database.

### Actual behavior

Errors upon database re-open, e.g. on btrfs:

```
Corruption: file is too short (2487 bytes) to be an sstable
```

Or, sometimes:

```
CURRENT file does not end with newline
```

### Steps to reproduce the behavior

1. Restore a backup a few times in a row
2. Cut power
3. Goto 1

My testbed for this includes a remote-controlled power switch, but it reliably happens within a few cycles. Tested on 6.20.3.

**Comment by ajkr** [comment]
> ### Expected behavior
> Power loss can cause loss of data (last N commits), but will not corrupt database.
> 
> ### Actual behavior
> Errors upon database re-open, e.g. on btrfs:
> 
> ```
> Corruption: file is too short (2487 bytes) to be an sstable
> ```
> 
> Or, sometimes:
> 
> ```
> CURRENT file does not end with newline
> ```

I think failing to open is good in case of an incomplete restore. It would be better if we could make sure it fails consistently and with a consistent error. We aren't able to drop a tail of data in case of incomplete restore because we don't retain the full history.

Proposal for restore:

1. Touch ".RESTORING" hidden file 
2. Fsync parent directory
3. Normal restore code
4. Unlink ".RESTORING"
5. Fsync parent directory

Proposal for DB open: add check for ".RESTORING" file's existence; if it exists, fail the open saying it's an incomplete restore.

cc @pdillinger for expert opinion.

My main hesitation towards this is it feels the application should be keeping track of what DBs restored successfully either way and only using those (and cleaning up ones that failed!), not relying on, e.g., a filesystem listing and attempting to open. But maybe it's a useful safety net.

**Comment by pdillinger** [comment]
I'd rather have backup code conform to DB code than the other way around. (We should be able to move CURRENT as last operation, fsync before and after.)

**Comment by ajkr** [comment]
Sounds good, I realized my proposal had gaps in the compatibility story anyways.

**Comment by Spferical** [comment]
>I think failing to open is good in case of an incomplete restore. It would be better if we could make sure it fails consistently and with a consistent error. We aren't able to drop a tail of data in case of incomplete restore because we don't retain the full history.

I want to make sure to emphasize that I saw corruption when power cycling after completing a restore, whereas I would expect restores to only be incomplete during the API call.

> I'd rather have backup code conform to DB code than the other way around. (We should be able to move CURRENT as last operation, fsync before and after.)

If I understand correctly, this could make restores fully atomic? That would be excellent!
