### ISSUE TITLE
RuntimeException: librocksdbjni-osx.jnilib was not found inside JAR

### ISSUE THREAD

**Issue by chnaik** [facebook/rocksdb#857]
I am having a maven project where I am using rockdb java dependency like:
     <dependency>
          <groupId>org.rocksdb</groupId>
          <artifactId>rocksdbjni</artifactId>
          <version>3.5.1</version>
      </dependency>
When I am running it in intellij, it is running fine but when I am trying to run it from the command line using mvn command, it is throwing the following exception:
Caused by: java.lang.RuntimeException: librocksdbjni-osx.jnilib was not found inside JAR.
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:34)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:50)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:28)
	... 27 more
mvn command used: mvn exec:java -Dexec.mainClass="com.application.Application"
Can someone please tell me what am I missing?

thanks

**Comment by adamretter** [comment]
@chnaik The latest version of RocksDB should include support for Mac OS X inside its Jar file.

**Comment by edtbl76** [comment]
as of 5.18.3 this is not the case. 
I compiled the JNI on a CentOS system and attempted to build an application that references that JNI:
Caused by: java.lang.RuntimeException: librocksdbjni-osx.jnilib was not found inside JAR.

[root@localhost target]# jar tf rocksdbjni-1.2.0-SNAPSHOT-linux64.jar | grep librocksdbjni*
librocksdbjni-linux64.so
[root@localhost target]# 

This was compiled w/ the PORTABLE=1 flag. 

The behavior contradicts the document here: 
https://github.com/facebook/rocksdb/blob/master/INSTALL.md  which suggests that compiling w/ the PORTABLE=1 option will create a portable binary.
