### ISSUE TITLE
GetLiveFilesMetaData does not return blob file metas in integrated BlobDB

### ISSUE THREAD

**Issue by sherriiiliu** [facebook/rocksdb#8626]
### Expected behavior
My understanding is `GetLiveFilesMetaData` API should get all live file metas, including .sst files and .blob files in integrated BlobDB, just like `GetLiveFiles`

### Actual behavior
Now in integrated BlobDB, `GetLiveFilesMetaData` only gets sst file metas, not including blob files, while `GetLiveFiles` can get a list of both sst and blob files, which means these two APIs does not match in behavior.
BTW, BlobDB based on StackableDB returns a list of both sst and blob file metas in `GetLiveFilesMetaData` as expected.

### Steps to reproduce the behavior
Open a db with integrated blobdb enabled, write some data and flush to generate some sst files and blob files. Call `GetLiveFilesMetaData` to see the list of file metas.
```cpp
    std::vector<LiveFileMetaData> live_file_metas;
    db->GetLiveFilesMetaData(&live_file_metas);
```
@ltamasi @mrambacher

**Comment by ltamasi** [comment]
This is by design. I consider what the old BlobDB does a bit of a hack, since it uses a structure meant for SST files in connection with blob files, so we didn't want to do the same here. (Note that `LiveFileMetaData` is derived from `SstFileMetaData` and has fields like level which are not relevant for blob files.) Since adding a new parameter to `GetLiveFilesMetaData` would have potentially broken clients, we decided to add a new API `GetAllColumnFamilyMetaData` that exposes a consistent view of SSTs+blob files for all column families.

**Comment by sherriiiliu** [comment]
> This is by design. I consider what the old BlobDB does a bit of a hack, since it uses a structure meant for SST files in connection with blob files, so we didn't want to do the same here. (Note that `LiveFileMetaData` is derived from `SstFileMetaData` and has fields like level which are not relevant for blob files.) Since adding a new parameter to `GetLiveFilesMetaData` would have potentially broken clients, we decided to add a new API `GetAllColumnFamilyMetaData` that exposes a consistent view of SSTs+blob files for all column families.

I see. Thanks @ltamasi for explanation! I will switch to use `GetAllColumnFamilyMetaData` API to fetch metadata of blob files
