### ISSUE TITLE
Difficult to find manuals / examples on how to use WAL Iterator.

### ISSUE THREAD

**Issue by hiqsociety** [facebook/rocksdb#8639]
possible to provide examples for using iterators? cant seem to find it in manual / doc / online

**Comment by zhichao-cao** [comment]
You may take a look at the wiki : https://github.com/facebook/rocksdb/wiki/Iterator also you can read the "seek" and "seekforprev" section for more information.

**Comment by riversand963** [comment]
How about trying the following in the rocksdb repo
```
git grep 'TransactionLogIterator' -- --incldue '*test*'
```
Open any of the search results, you should be able to see an example of TransactionLogIterator.

I am going to close this issue based on the following:
1. issues are mainly for bug reports/design discussion/confusing behavior
2. more importantly, this issue is asking for "examples", and the above command can achieve the goal.

We probably should add/update wiki about this topic, which can be tracked by something else.
