### ISSUE TITLE
Adding assertion for the LevelFiles(int level) reveales out of bounds access 

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#864]
Adding the following asserts makes the second one fail in reduce_levels_test

reduce_levels_test_je State: Completed
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from ReduceLevelTest
[ RUN      ] ReduceLevelTest.Last_Level
reduce_levels_test_je.exe : Assertion failed: level < num_levels_, file c:\dev\rocksdb\rocksdb\db\version_set.h, line 227

  const std::vector<FileMetaData*>& LevelFiles(int level) const {
    assert(level >= 0);
    assert(level < num_levels_);
    assert(files_ != nullptr);
     return files_[level];
   }

**Comment by chinyajie** [comment]
I have the same probloem.

**Comment by chinyajie** [comment]
> Adding the following asserts makes the second one fail in reduce_levels_test
> 
> reduce_levels_test_je State: Completed
> [==========] Running 3 tests from 1 test case.
> [----------] Global test environment set-up.
> [----------] 3 tests from ReduceLevelTest
> [ RUN ] ReduceLevelTest.Last_Level
> reduce_levels_test_je.exe : Assertion failed: level < num_levels_, file c:\dev\rocksdb\rocksdb\db\version_set.h, line 227
> 
> const std::vector<FileMetaData*>& LevelFiles(int level) const {
> assert(level >= 0);
> assert(level < num_levels_);
> assert(files_ != nullptr);
> return files_[level];
> }

I got it now.

Because in reduce_levels_test, the real level of files_ could be more(128) than  num_levels_. The arg level is got from Option, it would be the real level number, but num_levels_ not.
You can get more information in function VersionSet::ReduceNumberOfLevels.

It said 
  // we need to allocate an array with the old number of levels size to
  // avoid SIGSEGV in WriteSnapshot()
  // however, all levels bigger or equal to new_levels[num_levels_ in VersionStorage used this value] will be empty
