### ISSUE TITLE
org.rocksdb.RocksDBException CURRENT file does not end with newline; status : Corruption

### ISSUE THREAD

**Issue by ChenSammi** [facebook/rocksdb#8682]
Dear rocksdb community contributors, 

Our project uses rocksdb as the data meta store. After the services restarts, we failed to open the rocksdb and got this "CURRENT file does not end with newline" exception.  The CURRENT file is actually empty.  

CURRENT file is used as the index of latest meta file.  Is ther any way to recover this DB?  Further more, what can we do to prevent this isseue from happening?

**Comment by ajkr** [comment]
Do you use checkpoint and an old RocksDB version by any chance? Last I saw this problem was #4322 which should be fixed in RocksDB 5.17.0+.

If not, what is the RocksDB version and platform? Do you use either of checkpoint or backup?

For recovery, maybe make a copy of the DB directory in case something goes wrong, and then try recovering with `best_efforts_recovery=true`. Or if that's not possible/doesn't work, try craft the CURRENT file manually. It's just one line with the name of the latest successfully written manifest file (e.g., `MANIFEST-000010`).

**Comment by ChenSammi** [comment]
Thanks for the quick response.  We use 6.20.3 rocksdb jni on CentOS Linux release 7.9，and don't use the checkpoint so far. 

I'd like to confirm that the solution is "put MANIFEST file with the last number to CURRENT file", right?

**Comment by ajkr** [comment]
Yes. But copy the DB somewhere else first just in case. There's a nonzero chance the failure happened while writing the MANIFEST with the highest number, in which case you'll need to populate CURRENT file with the MANIFEST with the second highest number.
