### ISSUE TITLE
Huge write amplification

### ISSUE THREAD

**Issue by BenoitDuffez** [facebook/rocksdb#8989]
Hello

I'm using the Helium miner software: https://github.com/helium/miner that uses rocksdb with an Erlang wrapper.

This application writes about 1GB of net data every day (filesystem growth), however the block device indicators show that about 80GB is sent to the storage device, hence a write amplification of about 80.

I've been trying to understand how this could happen, I tried various configurations (number of levels, compaction algo, etc) but none of them change the behavior.

What would be a good troubleshooting procedure to understand what is the problem? I don't know if the application is sending too much to rocksdb, or if a rocksdb configuration change could fix this. I've monitored the disk writes with the rocksdb logs, most of them happen during compaction.

Thanks

**Comment by huachaohuang** [comment]
I think the `LOG` file is a good start. You can check the statistics about different activities and the level structures. Then you can try the [Tuning Guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide).
You may also give more details about your specific usages and configurations so that other people can help you.

**Comment by ajkr** [comment]
Sharing the LOG file, especially the table following "Compaction Stats" in the LOG, we may be able to take a look. Will reopen if you still need help with this.
