### ISSUE TITLE
rocksdbjni 6.26.0 is missing from maven central

### ISSUE THREAD

**Issue by ideco** [facebook/rocksdb#9176]
Hi,

I noticed that the newest version of rocksdb is missing from maven central (the newest one is 6.25.3)

![image](https://user-images.githubusercontent.com/1742378/142024406-04ee9514-0a7e-4934-afe1-2e9f836c8810.png)

Does it still need to be pushed to maven central?

Cheers,
Ivo

**Comment by flyingsilverfin** [comment]
Same request here!

**Comment by adamretter** [comment]
RocksJava 6.26.0 won't be released as there were issues with building the C++ code for it on some platforms. We are currently testing 6.26.1 for which there should be a RocksJava release - stay tuned...

**Comment by ideco** [comment]
Great, thanks for your efforts! Is there a place where we can see what will be released and what not (maybe in the release notes), or is it all internal? I find it a bit hard to have an overview and I don't think people opening issues all the time is very efficient.

**Comment by ajkr** [comment]
> Is there a place where we can see what will be released and what not

You can expect the latest minor version (currently 6.26) to be released once bugs are fixed on platforms Adam tests on and it's pushed to Maven central. What patch version that ends up being (e.g., 6.26.0 or 6.26.1) is not really predetermined. FWIW, we don't give a guarantee when GitHub tags will appear either.

I'll close this since the original question appears answered, but please still feel free to add any thoughts/opinions.

**Comment by adamretter** [comment]
@ideco There are some highlights in the release notes - https://github.com/facebook/rocksdb/releases ; although these are written at the time of release. You can also check the git tag or branch (6.26.fb). In addition there is the `HISTORY.md` file which has breaking changes listed.

**Comment by adamretter** [comment]
@ideco @flyingsilverfin 6.26.1 is now available from Maven Central.
