### ISSUE TITLE
[Discussion]let IncreaseFullHistoryTsLow be a public API

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#9210]
Currently, the fullHistoryTsLow is a member of CompactRangeOptions, that means a CF's fullHistoryTsLow  is advanced only when users submit a CompactRange request.
However, users may want to advance the fllHistoryTsLow without an immediate compact, users may construct a fake range(which actually does not exist in the db, and submit a CompactRange task with the fake range. This should work but not neat.
So, @riversand963 , how about make `IncreaseFullHistoryTsLow` a public API so users can advance each CF's fullHistoryTsLow seperately?

**Comment by riversand963** [comment]
@wolfkdy this sounds a reasonable ask. We avoided doing so in our first attempt because we wanted to defer the addition of public APIs. Also, the current implementation of increasing `full_history_ts_low` may have an edge case. If multiple threads try to increase the threshold at the same time, it will be increased to the max, but callers in different threads may not learn about the actual new value, as discussed in https://github.com/facebook/rocksdb/pull/7884#discussion_r572402281.
I hope this can be resolved.
Would you like to contribute this feature?

**Comment by wolfkdy** [comment]
> Would you like to contribute this feature?

@riversand963 Thanks, we'll try to post an mr in a week.
> I hope this can be resolved.

I think this can be resolved by also making the `GetFullHistoryTsLow` public, we can discuss about the details when the code is ready.

**Comment by sunlike-Lipo** [comment]
@riversand963 
I repost a pull request for this discussion.  https://github.com/facebook/rocksdb/pull/9221
