### ISSUE TITLE
blobdb space amplification unacceptable

### ISSUE THREAD

**Issue by leon-db** [facebook/rocksdb#9235]
In the new integrated blobdb, if there have many keys not update frequently, then there have no change to load the blob to a new one.  if the blob file size is 256MB and if there have only little valid key-values in the blob file, extremely there have one valid value in this blob file. if the sst file (which contains key reference to the only valid blob value) not picked by the compaction than there almost have about blob_file_size space size amplification. 
In our production env, there have about 2.x times space amplification that will be unacceptable.
![image](https://user-images.githubusercontent.com/7334994/144166715-9f3ce87b-986e-4c1c-b7d3-cb91235180b8.png)
obviously blob_garbage_collection_age_cutoff can only cover the keys that picked by the compaction.

one simply resolution is when we pick a sst file for compaction we take the garbage info of blob file refer by the sst file into account.

**Comment by ltamasi** [comment]
@leon-db See the configuration option `blob_garbage_collection_force_threshold` that we have added exactly for such skewed workloads. The tradeoff is that in order to decrease space amp, the additional compactions will increase write amp. 

BTW, is your space amp around 2? I wouldn't consider that particularly high.

**Comment by leon-db** [comment]
before we upgrade to blobdb it used about 1.3T after that the occupied space increased to 3TB.

**Comment by leon-db** [comment]
i think this config blob_garbage_collection_force_threshold is useful for us, we are use the old one which not have this configuration yet.

**Comment by ltamasi** [comment]
> before we upgrade to blobdb it used about 1.3T after that the occupied space increased to 3TB.

That's the tradeoff with key-value separation: you're trading space amp for write amp. You can use the options mentioned to tune the balance between the two. However, in general it's expected that space amp will be higher due to the presence of garbage blobs.

Another thing you might consider is using smaller blob files. Note however that that means more blob files for the same database size (which in turn means e.g. somewhat larger MANIFESTs).

**Comment by leon-db** [comment]
yes, with out this configuration(blob_garbage_collection_force_threshold). our resolution is adjust small blob files and enlarge cutoff_age threshold. i just wonder if there not have the blob_garbage_collection_force_threshold i am want to contribute this configuration too. now thanks that sounds great, and use this configuration i thank the tradeoff between space amp and write amp are much more controllable.
