### ISSUE TITLE
Can we open Discussions tab on Github for better communication?

### ISSUE THREAD

**Issue by pcpLiu** [facebook/rocksdb#9322]
The issue template suggest we ask non-bug questions in [Google forum](https://groups.google.com/forum/#!forum/rocksdb) or [Facebook group](https://www.facebook.com/groups/rocksdb.dev). The facebook group is obviously not a good platform asking coding related question. The google forum may be debatable, but the response on that one is also very low (The latest post was posted on 12-01 and no one responded yet).

Wondering if we can open the Discussions tab on this repo for more stackoverflow-ish (usage, best practice etc.) question? Many projects have did so.

For example, I wanna get more clear context about column family usage. Like are  `(CF1, key1, val1)` & `(CF2, key1, val2)` representing same object or two objects, i.e. is key space separated between CFs?

For this kind of question, other users may also know the answer and can help me in Discussion tab. And I think we agree that Github is currently the most accessible platform for most developers.

Thanks.

**Comment by mdcallag** [comment]
I agree with you, but it isn't my decision and I am not sure the response rates will change.

**Comment by ajkr** [comment]
> For example, I wanna get more clear context about column family usage. Like are (CF1, key1, val1) & (CF2, key1, val2) representing same object or two objects, i.e. is key space separated between CFs?

Two objects, each column family is a separate key space.

**Comment by ajkr** [comment]
Would it be similarly good if we remove the following text from the issue template: "Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev" ?

I am happy to answer questions in issues and apply the "question" label. People who want to see non-question issues can filter those out.

**Comment by adamretter** [comment]
@ajkr Does that mean that we would also shut the Google Group and Facebook Group? Personally, I prefer if questions and discussions happen in a single place rather than needing to monitor multiple places.

**Comment by ajkr** [comment]
I wasn't planning to ask for closing any group. Just wanted to propose changing the issue template because I personally am OK with answering questions here for people who feel the other forums are inadequate. But that still depends on other teammates feeling the same way as me, which we don't know yet.

**Comment by riversand963** [comment]
Trying to understand what is the problem we are trying to solve here.

More specifically, have you tried posting your questions to Google group/mail list/FB group and not having a response? I think the factor that determines whether a question is answered depends largely on **how hard the problem itself is** and **whether it is convenient for other people to catch up on the same page with you to get started**. For questions like the ones you asked here, I don't see why Google group/mail list/FB group cannot perform as well as Github discussion. For more complex questions, e.g. performance tuning, configuration, bug report, I doubt whether including Github Discussion will help, because we are not bottlenecked by the number of communication channels/forums.

One can argue that there are more RocksDB developers on Github than on other forums. This is likely the case :).

**Comment by ajkr** [comment]
> I wasn't planning to ask for closing any group. Just wanted to propose changing the issue template because I personally am OK with answering questions here for people who feel the other forums are inadequate. But that still depends on other teammates feeling the same way as me, which we don't know yet.

Actually I changed my mind. The template is useful since we (sort of) actively manage issues, and it gives us a way to close feature requests/questions that did not gain traction.

Also note the original question has been answered in an issue. Sometimes people practice civil disobedience and open issues for their questions that get answered. Or they don't gain traction and we close them eventually (as the template permits us to do).

Closing since I no longer plan to advocate for changes here. Someone else can claim and reopen if they wish.
