### ISSUE TITLE
Can we ingest the sst files from one RocksDB to another RocksDB?

### ISSUE THREAD

**Issue by liujiang0529** [facebook/rocksdb#9346]
I want to create a master and slave database Instance. For the slave,  I want to migrate master Stock data to slave use Ingest API. But occur errors. why not support this?

Corruption: External file version not found

**Comment by riversand963** [comment]
RocksDB supports ingesting external SST files created by `SstFileWriter`. Read operations need to handle the sequence numbers of the keys in these files differently to ensure correctness.
There are some differences in block format/content from regular SST files. That's why you saw the corruption.

You can do a logical dump from the primary by iterating all the keys, read them and write them to external SST files using SstFileWriter. On the slave side, you can ingest these SST files. I am afraid that this may not meet your requirement if performance is critical, since logical dump is slower than physically copying files around.

You didn't specify requirement on the interaction between primary and secondary. Do they have to be online? Does the secondary need to serve write? Are they in the same process and/or host with shared storage?
There is `DB::OpenAsSecondary`, but there are some limitations. Currently, you need to coordinate the primary and secondary so that the primary does not delete files used by the secondary serving read traffic. We plan to resolve this in the near future.

Checkpoint and backups are two other means of moving data around when RocksDB is used by other distributed databases. Not sure if they work in your case. You can find more information about them at https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB and https://github.com/facebook/rocksdb/wiki/Checkpoints.

Finally, we use Github issue mainly for bug report. Therefore, I am going to close this one. For questions/discussions, please use Google group (mail list) and/or FB group, mentioned in the issue template.
