### ISSUE TITLE
Estimating write amplification of integrated blobdb

### ISSUE THREAD

**Issue by sherriiiliu** [facebook/rocksdb#9532]
Hi, I am trying to tune different options of integrated blobdb to tradeoff between space and write amplification, but feel lack of guidance on tuning. @ltamasi do we have a math model to estimate write amplification of integrated blobdb something just like [universal compaction](https://github.com/facebook/rocksdb/wiki/Universal-Compaction)

**Comment by ltamasi** [comment]
Hi @sherriiiliu - we don't have a formal mathematical model but we do have some (still evolving) tuning guidance for BlobDB here: https://github.com/facebook/rocksdb/wiki/BlobDB#api.

For good write performance, one of the key points is to have a nicely shaped LSM tree since too few/large SST files can lead to heavy compactions/garbage collection. This translates to setting `target_file_size_base` to a much smaller value than `write_buffer_size`, and then setting `max_bytes_for_level_base` based on that. The usual guidance of `target_file_size_base==write_buffer_size` does not apply in the case of BlobDB because (depending on key and value sizes) only a small fraction of the data is written to SSTs during flush, which reduces the "natural" size of SSTs.

The wiki above suggests setting `blob_file_size==write_buffer_size`; however, from a space amp POV, note that space will be reclaimed in `blob_file_size` increments so you probably don't want to go too big here. That is, if your `write_buffer_size` is large, you might want to to experiment with values smaller than `write_buffer_size`. Another important option here is `blob_garbage_collection_force_threshold`: under the assumption that older blob files contain more garbage, setting this to `x` would mean a soft bound of `1/(1-x)` on the space amp associated with the blob files. (Side note: this space amp and the total amount of garbage is logged as part of the CF statistics since #9538).

**Comment by sherriiiliu** [comment]
> Hi @sherriiiliu - we don't have a formal mathematical model but we do have some (still evolving) tuning guidance for BlobDB here: https://github.com/facebook/rocksdb/wiki/BlobDB#api.
> 
> For good write performance, one of the key points is to have a nicely shaped LSM tree since too few/large SST files can lead to heavy compactions/garbage collection. This translates to setting `target_file_size_base` to a much smaller value than `write_buffer_size`, and then setting `max_bytes_for_level_base` based on that. The usual guidance of `target_file_size_base==write_buffer_size` does not apply in the case of BlobDB because (depending on key and value sizes) only a small fraction of the data is written to SSTs during flush, which reduces the "natural" size of SSTs.
> 
> The wiki above suggests setting `blob_file_size==write_buffer_size`; however, from a space amp POV, note that space will be reclaimed in `blob_file_size` increments so you probably don't want to go too big here. That is, if your `write_buffer_size` is large, you might want to to experiment with values smaller than `write_buffer_size`. Another important option here is `blob_garbage_collection_force_threshold`: under the assumption that older blob files contain more garbage, setting this to `x` would mean a soft bound of `1/(1-x)` on the space amp associated with the blob files. (Side note: this space amp and the total amount of garbage is logged as part of the CF statistics since #9538).

Thanks @ltamasi  for the clear guidance. The newly added log looks quite helpful for us to quickly track the garbage amount and blobdb space amplification in periodic stats report. I will follow your suggestions to tune the options
