### ISSUE TITLE
verify_checksums is ignored in rocksdbjni

### ISSUE THREAD

**Issue by cavallium** [facebook/rocksdb#9718]
when creating a db iterator with column family handle and ReadOptions, the option "setVerifyChecksums" is ignored

### Expected behavior

The database is iterated without verifying any checksum

### Actual behavior

Checksums are being verified:
![image](https://user-images.githubusercontent.com/8604780/159075011-a8c6e681-379f-4e92-80f7-7973aa07940d.png)

### Steps to reproduce the behavior

```java
var readOptions = new ReadOptions();
readOptions.setReadaheadSize(32 * 1024);
readOptions.setFillCache(false);
readOptions.setVerifyChecksums(false);
var rocksIterator = db.newIterator(cfh, readOptions);
rocksIterator.seekToFirst();
rocksIterator.status();
while (rocksIterator.isValid()) {
  var k = rocksIterator.key();
  var v = rocksIterator.value();
  rocksIterator.next();
  rocksIterator.status();
}
```

**Comment by andrew-ld** [comment]
analysing rocksdb's code I saw that in many parts where a BlockFetcher instance is created an empty ReadOptions instance is passed in the constructor, I think our problem exists because of this.

https://github.com/facebook/rocksdb/blob/a8a422e96205015ab9a32cfdb89a48c3f831e8a9/table/meta_blocks.cc#L526

https://github.com/facebook/rocksdb/blob/a8a422e96205015ab9a32cfdb89a48c3f831e8a9/table/meta_blocks.cc#L487

https://github.com/facebook/rocksdb/blob/a8a422e96205015ab9a32cfdb89a48c3f831e8a9/table/block_based/block_based_table_reader.cc#L3056

**Comment by andrew-ld** [comment]
when analyzing the jni code it can be seen that the opts are set correctly.

https://github.com/facebook/rocksdb/blob/9e05c5e2519444faaf147a79e842853cee6f20ff/java/rocksjni/options.cc#L7887

but during the iteration the checksum is checked on BlockFetcher and looking at the comment above you can tell that the instance of the options that is passed to BlockFetcher is not the same as the one that is passed by jni.

https://github.com/facebook/rocksdb/blob/babe56ddbaae13877c896ac8d544c00d9219a374/table/block_fetcher.cc#L34

Translated with www.DeepL.com/Translator (free version)
