### ISSUE TITLE
Question：How to run Rocksdb Multi-thread in YCSBC?

### ISSUE THREAD

**Issue by renjc0816** [facebook/rocksdb#9902]
Ok it`s due to i am newbee, but is there anyone konw how to run Multi-thread rocksdb in YCSBC?
(Not YCSBC Multi-thread itselfs)
o(╥﹏╥)o

**Comment by jay-zhuang** [comment]
does this help: https://github.com/Colins110/YCSB-C-RocksDB

**Comment by adamretter** [comment]
I contributed the original RocksDB code to YCSB, however as YCSB is in Java, it uses the RocksJava API.

The JNI interface has some overhead, so the results with RocksJava will be less than those of using RocksDB from C or C++. If you want C or C++ then @jay-zhuang's suggestion is likely the way to go. Otherwise if you want Java you can use https://github.com/brianfrankcooper/YCSB/tree/master/rocksdb

**Comment by renjc0816** [comment]
Thanks for your help, i don`t konw how to reply comment so i add a new comment here.
Maybe it's because I didn't describe it clearly enough...
I run rocksdb in YCSBC ok but in single thread,now i want to run Multi-thread rocksdb in YCSBC.The parameter of '-threads 8' only change the threads of ycsbc itself not rocksdb,i want know how to make rocksdb run in Multi-thread (rocksdb default in single thread) not YCSBC.
Could anyone help me?....o(╥﹏╥)o....
