### ISSUE TITLE
Read-Only and Catch-Up

### ISSUE THREAD

**Issue by ronag** [facebook/rocksdb#9967]
I'm reading up on read only instances and there are some things that are unclear to me:

- Do read-only instances only work on a snapshot of the db from when it was opened? Or are writes in the primary immediately or eventually visible for reads in the read-only instances?
- What exactly does "catch up" mean? It's mentioned multiple times but never really explained.

**Comment by riversand963** [comment]
A few (re)-clarifications on terminology.
"read-only instances" -> `DBImplReadOnly` -> opened by `DB::OpenForReadOnly()`.
"secondary instance" => `DBImplSecondary` -> opened by `DB::OpenAsSecondary()`.

Read-only instances has only the state of the db when the read-only instance is opened. It's not meant to be used when the db is also opened by a normal DB instance. The normal db instance can cause file deletions unaware to the read-only instance. Future reads issued to the read-only instance may hit IOError due to trying to read from non-existing files.

`catch up` is an API which only secondary instance supports. Secondary instance can call `TryCatchUpWithPrimary()` to replay the WALs and MANIFESTs of the primary instance and update in-memory state.

**Comment by vt-alt** [comment]
@riversand963 Can you explain (or better add into FAQ) about single writer with one or multiple reader scenario? Is it safe for reader with DB::OpenForReadOnly?

I have reader in one process which DB::OpenForReadOnly and serve http requests and some infrequent updates by other processes to the database, and their DB:Open never signal any access errors. Is it safe? By reading your comment I assume it isn't.

Also, the reader (server) never sees new data from updaters. I wonder what is best practices for reader in such cases - OpenForReadOnly is quite slow operation and cannot be used for every request, thus it should be reopened sometimes. But how to detect when?

(Unfortunately code is in ruby and rocksdb-ruby gem does not support OpenAsSecondary, so I only have OpenForReadOnly).
